from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
from pathlib import Path

from weird_captcha_gym.realtime import load_real_time_settings
from weird_captcha_gym.shared_scripts.setup_task import generate_task_state


ROOT = Path(__file__).resolve().parents[1]
BENCHMARK = ROOT / "weird_captcha_gym"
ENVIRONMENT = BENCHMARK / "environments" / "ribbon_switchboard_env"
BASE_TASK_PATH = ENVIRONMENT / "tasks" / "ribbon_switchboard_seed_0001" / "task.json"


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


MATERIALIZER = _load("ribbon_switchboard_materializer", BENCHMARK / "tools" / "materialize_controlled_tasks.py")
GRADER = _load(
    "ribbon_switchboard_control_grader",
    BENCHMARK / "shared_runtime" / "server" / "incubator_graders" / "ribbon_switchboard.py",
)
GENERATOR = _load(
    "ribbon_switchboard_control_generator",
    BENCHMARK / "shared_scripts" / "incubator_generators" / "ribbon_switchboard.py",
)
CONTROLS = json.loads((ENVIRONMENT / "controls.json").read_text(encoding="utf-8"))
BASE_TASK = json.loads(BASE_TASK_PATH.read_text(encoding="utf-8"))
# Canonical digests for the 64 fixed states generated by the historical
# pre-control implementation.  They make a baseline drift visible even if an
# uncontrolled path is accidentally changed in lockstep with controlled L4.
HISTORICAL_UNCONTROLLED_STATE_DIGEST = "1a20d1aa7afadcb5f1d5d3b2ed556fe7033a89c17df03fffecd03a37ac74c1e8"
HISTORICAL_L4_WORLD_DIGEST = "d256b0c936c4e47b07459b2140d2c26691ef74c8a416a6659468eccdeadce8ab"


def _task(level: int, interaction: str) -> dict:
    return MATERIALIZER.controlled_task(
        BASE_TASK,
        mechanic_id="ribbon_switchboard",
        level=level,
        interaction=interaction,
        profile=CONTROLS["difficulty"][str(level)],
        task_dir_name=f"ribbon_switchboard_d{level}_{interaction}_seed_0001",
    )


def _without_control_identity(value: dict, *, remove_prompt: bool = False) -> dict:
    copied = copy.deepcopy(value)
    for field in ("task_id", "challenge_id", "control_condition"):
        copied.pop(field, None)
    if remove_prompt:
        copied.pop("prompt", None)
    return copied


def _state_digest(values: list[dict]) -> str:
    canonical = json.dumps(values, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def _passing_payload(truth: dict, interaction: str) -> dict:
    path = truth["target_path"]
    events: list[dict] = []

    def source(kind: str) -> str:
        if kind == "hover_probe":
            return "coordinate_hover" if interaction == "simplified" else "direct_pointer_hover"
        return "coordinate_trace" if interaction == "simplified" else "direct_pointer_trace"

    def record(kind: str, **details: object) -> None:
        events.append({"sequence": len(events) + 1, "kind": kind, "input_source": source(kind), **details})

    # Full-path probes are a deterministic replay fixture, not a claim about a
    # normal screenshot-only policy. They make every required coverage value
    # independently recomputable by the grader.
    for point in path:
        record("hover_probe", point=point)
    record("trace_start", raw=path[0], sample_index=0, elapsed_ms=0)
    for index, point in enumerate(path[1:], start=1):
        record("trace_sample", raw=point, sample_index=index, elapsed_ms=index * 12)
    record("trace_end", raw=path[-1], sample_index=len(path) - 1, elapsed_ms=(len(path) - 1) * 12)
    cells = {f"{point[0] // 55}:{point[1] // 55}" for point in path}
    return {
        "mechanic_id": "ribbon_switchboard",
        "challenge_id": truth["challenge_id"],
        "interaction": interaction,
        "events": events,
        "hover_count": len(path),
        "explored_cells": len(cells),
        "target_coverage": len(path),
        "crossing_coverage": len(truth["target_crossings"]),
        "trace_samples": len(path) - 1,
        "crossings_followed": len(truth["target_crossings"]),
        "collisions": 0,
        "rearm_count": 0,
        "final_point": path[-1],
        "completed": True,
    }


def test_controls_materialize_the_ten_conditions_and_preserve_l4_full(tmp_path: Path) -> None:
    MATERIALIZER.validate_controls(CONTROLS, ENVIRONMENT)
    assert CONTROLS["baseline"] == {"difficulty": 4, "interaction": "full", "real_time": "live"}
    assert CONTROLS["real_time"] == load_real_time_settings("ribbon_switchboard").__dict__
    written = MATERIALIZER.materialize_environment(ENVIRONMENT, tmp_path)
    assert {
        (json.loads((path / "task.json").read_text())["metadata"]["control_condition"]["difficulty"], json.loads((path / "task.json").read_text())["metadata"]["control_condition"]["interaction"])
        for path in written
    } == {(level, interaction) for level in range(1, 6) for interaction in ("simplified", "full")}

    historical_uncontrolled_states: list[dict] = []
    historical_l4_world_states: list[dict] = []
    for index in range(64):
        seed = f"audit-historical-ribbon-{index}"
        original_public, original_truth = generate_task_state(BASE_TASK, seed)
        baseline_public, baseline_truth = generate_task_state(_task(4, "full"), seed)
        assert original_public["challenge_id"] == baseline_public["challenge_id"]
        assert original_truth["challenge_id"] == baseline_truth["challenge_id"]
        assert _without_control_identity(original_public) == _without_control_identity(baseline_public)
        assert _without_control_identity(original_truth) == _without_control_identity(baseline_truth)
        historical_uncontrolled_states.extend((original_public, original_truth))
        historical_l4_world_states.extend((
            _without_control_identity(baseline_public),
            _without_control_identity(baseline_truth),
        ))
    assert _state_digest(historical_uncontrolled_states) == HISTORICAL_UNCONTROLLED_STATE_DIGEST
    assert _state_digest(historical_l4_world_states) == HISTORICAL_L4_WORLD_DIGEST


def test_difficulty_profiles_change_the_weave_and_interaction_preserves_it() -> None:
    for level in range(1, 6):
        parameters = CONTROLS["difficulty"][str(level)]["parameters"]
        simplified_public, simplified_truth = generate_task_state(_task(level, "simplified"), f"ribbon-profile-{level}")
        full_public, full_truth = generate_task_state(_task(level, "full"), f"ribbon-profile-{level}")
        assert simplified_public["challenge_id"] == full_public["challenge_id"]
        assert _without_control_identity(simplified_public, remove_prompt=True) == _without_control_identity(full_public, remove_prompt=True)
        assert _without_control_identity(simplified_truth) == _without_control_identity(full_truth)
        assert parameters["ribbon_count_min"] <= len(full_truth["ribbons"]) <= parameters["ribbon_count_max"]
        assert len(full_truth["target_crossings"]) >= parameters["min_target_crossings"]
        assert parameters["hover_radius_min"] <= full_truth["hover_radius"] <= parameters["hover_radius_max"]
        assert parameters["corridor_radius_min"] <= full_truth["corridor_radius"] <= parameters["corridor_radius_max"]
        assert full_truth["requirements"]["min_trace_samples"] >= parameters["min_trace_samples"]

    low_public, low_truth = generate_task_state(_task(1, "full"), "ribbon-profile-comparison")
    high_public, high_truth = generate_task_state(_task(5, "full"), "ribbon-profile-comparison")
    assert len(low_truth["ribbons"]) < len(high_truth["ribbons"])
    assert len(low_truth["target_path"]) < len(high_truth["target_path"])
    assert low_truth["corridor_radius"] > high_truth["corridor_radius"]
    assert low_truth["hover_radius"] > high_truth["hover_radius"]
    assert low_public["challenge_id"] != high_public["challenge_id"]


def test_grader_accepts_each_surface_and_rejects_other_mode_transcripts() -> None:
    for level in range(1, 6):
        simplified_public, simplified_truth = generate_task_state(_task(level, "simplified"), f"ribbon-replay-{level}")
        full_public, full_truth = generate_task_state(_task(level, "full"), f"ribbon-replay-{level}")
        simplified_payload = _passing_payload(simplified_truth, "simplified")
        full_payload = _passing_payload(full_truth, "full")
        assert GRADER.grade(simplified_payload, simplified_truth, simplified_public)["passed"] is True
        assert GRADER.grade(full_payload, full_truth, full_public)["passed"] is True

        wrong_mode = copy.deepcopy(full_payload)
        wrong_mode["challenge_id"] = simplified_truth["challenge_id"]
        rejected = GRADER.grade(wrong_mode, simplified_truth, simplified_public)
        assert rejected["passed"] is False
        assert "interaction" in rejected["feedback"]

        wrong_source = copy.deepcopy(simplified_payload)
        wrong_source["events"][0]["input_source"] = "direct_pointer_hover"
        rejected = GRADER.grade(wrong_source, simplified_truth, simplified_public)
        assert rejected["passed"] is False
        assert "wrong interaction input" in rejected["feedback"]


def test_l5_generates_every_retry_seed_in_the_stress_sample() -> None:
    parameters = CONTROLS["difficulty"]["5"]["parameters"]
    for interaction in ("simplified", "full"):
        for index in range(80):
            public, truth = generate_task_state(_task(5, interaction), f"ribbon-l5-retry-stress-{interaction}-{index}")
            assert len(truth["ribbons"]) == 6
            assert len(truth["target_crossings"]) >= 7
            assert parameters["hover_radius_min"] <= truth["hover_radius"] <= parameters["hover_radius_max"]
            assert parameters["corridor_radius_min"] <= truth["corridor_radius"] <= parameters["corridor_radius_max"]
            assert public["control_condition"] == truth["control_condition"]


def test_l5_fallback_layout_is_valid_for_every_target_bus() -> None:
    parameters = CONTROLS["difficulty"]["5"]["parameters"]
    for target_index in range(1, 7):
        ribbons, _crossings, audit = GENERATOR._dense_fallback_layout(parameters, f"ribbon-{target_index}")
        assert len(ribbons) == 6
        assert audit["target_crossing_count"] >= 7
        assert audit["maximum_close_run"] <= parameters["maximum_close_run"]


def test_browser_mechanic_declares_both_input_surfaces() -> None:
    source = (BENCHMARK / "shared_runtime" / "app" / "mechanics" / "ribbon_switchboard.js").read_text(encoding="utf-8")
    assert "ribbon-coordinate-controls" in source
    assert "coordinate_hover" in source
    assert "coordinate_trace" in source
    assert "direct_pointer_hover" in source
    assert "direct_pointer_trace" in source
    assert "data-interaction" in source
