(() => {
'use strict';
let m;
function initial(s,wheels,rods){const b=[[...s.parcel.slice(0,2),s.parcel[2],0],...wheels.map(w=>[...w])];return {b,v:b.map(()=>[0,0]),rods:rods.map(([a,c])=>[a,c,Math.hypot(b[a][0]-b[c][0],b[a][1]-b[c][1])]),tick:0,delivered:false};}
function step(s,sim){const b=sim.b,old=b.map(p=>p.slice(0,2)),contacts={};b.forEach((p,i)=>{const v=sim.v[i];v[0]*=.999;v[1]=v[1]*.999+.16;p[0]+=v[0];p[1]+=v[1];});
for(let j=0;j<12;j++){
 for(const [a,c,length] of sim.rods){const dx=b[c][0]-b[a][0],dy=b[c][1]-b[a][1],dist=Math.hypot(dx,dy);if(dist>1e-9){const k=(dist-length)/dist*.5;b[a][0]+=dx*k;b[a][1]+=dy*k;b[c][0]-=dx*k;b[c][1]-=dy*k;}}
 b.forEach((p,i)=>{for(const q of b.slice(i+1)){const dx=q[0]-p[0],dy=q[1]-p[1],d=Math.hypot(dx,dy),r=p[2]+q[2];if(d>1e-9&&d<r){const k=(r-d)/d*.5;p[0]-=dx*k;p[1]-=dy*k;q[0]+=dx*k;q[1]+=dy*k;}}
 for(const [x,y,xx,yy] of s.segments){const dx=xx-x,dy=yy-y,t=Math.max(0,Math.min(1,((p[0]-x)*dx+(p[1]-y)*dy)/(dx*dx+dy*dy)));let nx=p[0]-x-t*dx,ny=p[1]-y-t*dy;const d=Math.hypot(nx,ny),r=p[2]+3;if(d>1e-9&&d<r){nx/=d;ny/=d;p[0]+=nx*(r-d);p[1]+=ny*(r-d);contacts[i]=[nx,ny];}}});}
 b.forEach((p,i)=>{let vx=p[0]-old[i][0],vy=p[1]-old[i][1];if(contacts[i]){const [nx,ny]=contacts[i],vn=vx*nx+vy*ny;if(vn<0){vx-=vn*nx;vy-=vn*ny;}const tx=-ny,ty=nx,speed=vx*tx+vy*ty,target=p[3]*p[2]*.045,change=Math.max(-.18,Math.min(.18,target-speed));vx+=tx*change;vy+=ty*change;}sim.v[i]=[vx,vy];});sim.tick++;const [x,y,r]=b[0],[x0,y0,x1,y1]=s.receiver;sim.delivered=x-r>=x0&&x+r<=x1&&y-r>=y0&&y+r<=y1;return sim.delivered;}
function rec(kind,data={}){m.events.push({kind,...data});}
function msg(text,status='idle'){m.h.setReadout(text,status);}
function bodies(){return m.sim?m.sim.b:[[...m.s.parcel,0],...m.wheels];}
function point(e){const r=m.canvas.getBoundingClientRect(),style=getComputedStyle(m.canvas),left=parseFloat(style.borderLeftWidth)||0,top=parseFloat(style.borderTopWidth)||0,width=r.width-left-(parseFloat(style.borderRightWidth)||0),height=r.height-top-(parseFloat(style.borderBottomWidth)||0);return [Math.round((e.clientX-r.left-left)*920/width),Math.round((e.clientY-r.top-top)*480/height)];}
function hit(p){return bodies().findIndex(b=>Math.hypot(b[0]-p[0],b[1]-p[1])<=Math.max(b[2],15));}
function source(){return m.mode==='full'?'drag':'click';}
function editAction(kind,data){rec(kind,{...data,input_source:source()});msg('WORKBENCH · Design updated.');draw();}
function place(p,index=null){if(m.sim||m.terminal)return;const r=index?m.wheels[index-1][2]:m.radius;const [x0,y0,x1,y1]=m.s.build_box;if(p[0]-r<x0||p[0]+r>x1||p[1]-r<y0||p[1]+r>y1){msg('Keep the whole wheel inside the workbench.','error');return;}if(index){m.wheels[index-1][0]=p[0];m.wheels[index-1][1]=p[1];editAction('move',{index,point:p});}else if(m.wheels.length<m.s.max_wheels){const wheel=[...p,r,m.direction];m.wheels.push(wheel);editAction('place',{wheel:[...wheel]});}else msg('Wheel rack empty. Remove a wheel to reuse it.','error');}
function rod(a,b){if(a<0||b<0||a===b||m.rods.length>=m.s.max_rods)return;const ends=[Math.min(a,b),Math.max(a,b)];if(m.rods.some(r=>r[0]===ends[0]&&r[1]===ends[1]))return;m.rods.push(ends);editAction('rod',{ends});}
function rodAt(point){const b=bodies();let nearest=null,best=10;for(const ends of m.rods){const a=b[ends[0]],c=b[ends[1]],dx=c[0]-a[0],dy=c[1]-a[1],length=dx*dx+dy*dy;if(!length)continue;const t=Math.max(0,Math.min(1,((point[0]-a[0])*dx+(point[1]-a[1])*dy)/length)),distance=Math.hypot(point[0]-a[0]-t*dx,point[1]-a[1]-t*dy);if(distance<best){best=distance;nearest=ends;}}return nearest;}
function removeRod(point){const ends=rodAt(point);if(!ends){msg('Click the rod you want to remove.','pending');return;}m.rods=m.rods.filter(edge=>edge!==ends);editAction('unrod',{ends:[...ends]});}
function endRun(){m.running=false;rec('finish',{ticks:m.sim.tick});msg(m.sim.delivered?'DELIVERED · Certify your courier.':'RUN FAILED · Return to workbench and revise.',m.sim.delivered?'passed':'error');draw();}
function run(){if(m.sim||m.terminal)return;const b=bodies();if(b.some((p,i)=>b.slice(i+1).some(q=>Math.hypot(p[0]-q[0],p[1]-q[1])<p[2]+q[2]-.01))){msg('RUN BLOCKED · Bodies overlap. Move them apart.','error');return;}m.sim=initial(m.s,m.wheels,m.rods);rec('run');m.running=true;msg('TEST RUN · Watch the parcel and wheel contacts.','pending');draw();}
function edit(){if(m.terminal)return;if(m.running)endRun();if(m.sim){rec('edit');m.sim=null;}m.selected=null;m.drag=null;msg('WORKBENCH · Design retained. Adjust and run again.');draw();}
function draw(){if(!m)return;const c=m.canvas.getContext('2d');c.fillStyle='#102d35';c.fillRect(0,0,920,480);c.strokeStyle='#23434a';c.lineWidth=1;for(let x=20;x<920;x+=25){c.beginPath();c.moveTo(x,0);c.lineTo(x,480);c.stroke();}for(let y=10;y<480;y+=25){c.beginPath();c.moveTo(0,y);c.lineTo(920,y);c.stroke();}
const [x0,y0,x1,y1]=m.s.build_box;c.fillStyle='#d5ae6020';c.fillRect(x0,y0,x1-x0,y1-y0);c.strokeStyle='#bdab72';c.setLineDash([6,6]);c.strokeRect(x0,y0,x1-x0,y1-y0);c.setLineDash([]);c.font='bold 14px monospace';c.fillStyle='#ead7ab';c.fillText('WORKBENCH',x0,145);
const [gx,gy,gxx,gyy]=m.s.receiver;c.fillStyle='#6bd4aa25';c.fillRect(gx,gy,gxx-gx,gyy-gy);c.strokeStyle='#8cf2c0';c.lineWidth=2;c.strokeRect(gx,gy,gxx-gx,gyy-gy);c.fillStyle='#a9f7cd';c.fillText('RECEIVER',gx,gy-12);
for(const [segmentIndex,[x,y,xx,yy]]of m.s.segments.entries()){c.strokeStyle='#e4c68a';c.lineWidth=6;c.lineCap='round';c.beginPath();c.moveTo(x,y);c.lineTo(xx,yy);c.stroke();if(y>300&&!m.s.overhead_segments?.includes(segmentIndex)){c.strokeStyle='#947b5055';c.lineWidth=2;for(let px=x+15;px<xx;px+=40){const py=y+(yy-y)*(px-x)/(xx-x);c.beginPath();c.moveTo(px,py+4);c.lineTo(px-20,480);c.stroke();}}}
const b=bodies();for(const [a,d]of m.rods){c.strokeStyle='#7dd6e4';c.lineWidth=6;c.beginPath();c.moveTo(b[a][0],b[a][1]);c.lineTo(b[d][0],b[d][1]);c.stroke();c.strokeStyle='#c4f1ef';c.lineWidth=1;c.stroke();}
b.forEach((p,i)=>{const [x,y,r,d]=p;c.save();c.translate(x,y);c.fillStyle=i?'#b98941':'#ef796b';c.strokeStyle=i?'#ffe4a1':'#ffd6ae';c.lineWidth=3;c.beginPath();c.arc(0,0,r-1.5,0,Math.PI*2);c.fill();c.stroke();if(i){c.rotate((m.sim?.tick||0)*d*.045);c.strokeStyle='#4f431f';c.lineWidth=5;for(let j=0;j<6;j++){c.rotate(Math.PI/3);c.beginPath();c.moveTo(8,0);c.lineTo(r-6,0);c.stroke();}}else{c.strokeStyle='#ffe9be';c.lineWidth=4;c.strokeRect(-9,-9,18,18);}c.restore();c.fillStyle='#eaf4d9';c.beginPath();c.arc(x,y,7,0,Math.PI*2);c.fill();if(i){c.font='bold 20px sans-serif';c.fillStyle='#fff0bb';c.fillText(d>0?'↻':'↺',x-9,y-r-8);}if(m.selected===i){c.strokeStyle='white';c.lineWidth=2;c.beginPath();c.arc(x,y,r+7,0,Math.PI*2);c.stroke();}});
if(m.drag&&m.tool==='rod'&&m.drag.index>=0){const p=b[m.drag.index];c.strokeStyle='white';c.lineWidth=3;c.beginPath();c.moveTo(p[0],p[1]);c.lineTo(...m.drag.point);c.stroke();}
if(m.drag&&(m.drag.rack||m.tool==='move')){const r=m.drag.rack?m.radius:(m.wheels[m.drag.index-1]?.[2]||m.radius);c.globalAlpha=.7;c.fillStyle='#f5cb6b';c.beginPath();c.arc(...m.drag.point,r,0,Math.PI*2);c.fill();c.globalAlpha=1;}
if(m.sim&&!m.running){c.fillStyle=m.sim.delivered?'#9bf2bc':'#ffb399';c.font='bold 26px sans-serif';c.fillText(m.sim.delivered?'PARCEL DELIVERED':'RUN FAILED',365,65);}
document.querySelector('.cc-count').textContent=`${m.wheels.length} / ${m.s.max_wheels} wheels · ${m.rods.length} / ${m.s.max_rods} rods`;document.querySelector('.cc-run').disabled=!!m.sim||m.terminal;
}
async function submit(){if(m.busy||m.running||m.terminal)return;m.busy=true;const payload={mechanic_id:m.s.mechanic_id,task_id:m.s.task_id,challenge_id:m.s.challenge_id,events:m.events};try{const out=await(await fetch('/result',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})).json();if(out.passed){m.terminal=true;msg('PASS','passed');document.querySelector('.cc-verdict').textContent='PASS · DELIVERY CERTIFIED';}else if(out.state){await m.h.render(out.state);msg('FAIL · Fresh workshop issued.','error');}else msg('FAIL · Delivery not verified.','error');}catch(e){msg('Verification unavailable. Retry certification.','error');}m.busy=false;}
async function render(s,h){if(m?.timer)clearInterval(m.timer);document.body.dataset.mechanic='clockwork-courier-works';const mode=s.control_condition?.interaction||'full';h.app.innerHTML=`<section class="cc-workshop"><header><div><small>FIELD POST / MECHANICAL DELIVERY DIVISION</small><h1>Clockwork Courier Works</h1></div><strong>BUILD → TEST → REVISE</strong></header><div class="cc-layout"><canvas width="920" height="480" class="cc-canvas"></canvas><aside><h2>Parts cabinet</h2><p class="cc-instruction">${mode==='full'?'Drag a wheel from its rack onto the workbench.':'Choose a wheel, then click in the workbench.'}</p><div class="cc-rack">${s.wheel_radii.map(r=>`<button data-radius="${r}">◉ ${r*2}</button>`).join('')}</div><button class="cc-direction">Motor ↻</button><button class="cc-tool" data-tool="move">Move wheel</button><button class="cc-tool" data-tool="rod">Connect rod</button><p>${mode==='full'?'Drag between hubs to join them.':'Click two hubs to join them.'} Rods pass through objects.</p><button class="cc-tool" data-tool="reverse">Reverse motor</button><button class="cc-tool" data-tool="delete">Remove wheel</button><button class="cc-tool" data-tool="unrod">Remove rod</button><p class="cc-count"></p><button class="cc-edit">↶ Workbench</button><small>Only wheels and the parcel collide. No prescribed machine shape.</small></aside></div><footer><div class="readout" data-status="idle">Build a courier for the coral parcel.</div><button class="cc-run">▶ Run machine</button><button class="cc-submit">Certify delivery</button></footer><div class="cc-verdict"></div></section>`;
m={s,h,mode,wheels:[],rods:[],events:[],sim:null,running:false,tool:'place',radius:36,direction:1,selected:null,drag:null,canvas:document.querySelector('.cc-canvas'),terminal:false};
const canvas=m.canvas;
for(const button of document.querySelectorAll('[data-radius]')){button.addEventListener('click',()=>{m.radius=+button.dataset.radius;m.tool='place';m.selected=null;msg('Wheel selected · '+(mode==='full'?'drag from rack to workbench.':'click to place.'));});if(mode==='full')button.addEventListener('pointerdown',e=>{if(m.sim)return;e.preventDefault();m.radius=+button.dataset.radius;m.tool='place';m.drag={rack:true,point:point(e)};button.setPointerCapture(e.pointerId);});if(mode==='full')button.addEventListener('pointermove',e=>{if(m.drag?.rack){m.drag.point=point(e);draw();}});if(mode==='full')button.addEventListener('pointercancel',()=>{m.drag=null;draw();});if(mode==='full')button.addEventListener('pointerup',e=>{if(m.drag?.rack){place(point(e));m.drag=null;draw();}});}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{m.tool=b.dataset.tool;m.selected=null;msg(`${b.textContent} · ${mode==='full'&&['move','rod'].includes(m.tool)?'drag on the workbench.':'click the wheel or hub.'}`);draw();});document.querySelector('.cc-direction').onclick=e=>{m.direction*=-1;e.target.textContent='Motor '+(m.direction>0?'↻':'↺');};
canvas.onpointerdown=e=>{if(m.sim||m.terminal||e.button!==0)return;e.preventDefault();const p=point(e),i=hit(p);if(m.tool==='unrod'){removeRod(p);return;}if(['reverse','delete'].includes(m.tool)&&i>0){if(m.tool==='reverse'){m.wheels[i-1][3]*=-1;editAction('reverse',{index:i});}else{m.wheels.splice(i-1,1);m.rods=m.rods.filter(r=>!r.includes(i)).map(r=>r.map(a=>a-(a>i)));editAction('delete',{index:i});}return;}if(mode==='full'){if(m.tool==='place')return;m.drag={index:i,point:p};canvas.setPointerCapture(e.pointerId);}else if(m.tool==='place')place(p);else if(m.tool==='rod'){if(m.selected===null)m.selected=i;else{rod(m.selected,i);m.selected=null;}}else if(m.tool==='move'){if(m.selected===null)m.selected=i>0?i:null;else{place(p,m.selected);m.selected=null;}}draw();};
canvas.onpointermove=e=>{if(m.drag){m.drag.point=point(e);draw();}};canvas.onpointerup=e=>{if(!m.drag)return;const d=m.drag;m.drag=null;if(m.tool==='rod')rod(d.index,hit(point(e)));else if(m.tool==='move'&&d.index>0)place(point(e),d.index);draw();};canvas.onpointercancel=()=>{m.drag=null;draw();};
document.querySelector('.cc-run').onclick=run;document.querySelector('.cc-edit').onclick=edit;document.querySelector('.cc-submit').onclick=submit;
m.timer=setInterval(()=>{if(m.running){step(m.s,m.sim);if(m.sim.delivered||m.sim.tick>=m.s.max_ticks||m.sim.b[0][1]>550)endRun();draw();}},s.tick_ms);draw();}
window.WeirdCaptchaMechanics=window.WeirdCaptchaMechanics||{};window.WeirdCaptchaMechanics.clockwork_courier_works={rootSelector:'.cc-workshop',render};
})();
