(() => {
  'use strict';
  let model, timer, cleanup;
  const clone=x=>JSON.parse(JSON.stringify(x)), q=x=>Math.floor(x*1e6+.5)/1e6;
  function pose(c){return c.lane===0?{x:c.s,y:290,a:0,v:c.v}:c.lane===1?{x:900-c.s,y:230,a:Math.PI,v:c.v}:{x:420,y:c.s,a:Math.PI/2,v:c.v};}
  function corners(c){const co=Math.cos(c.a),si=Math.sin(c.a);return [[-20,-11],[20,-11],[20,11],[-20,11]].map(([u,v])=>[c.x+u*co-v*si,c.y+u*si+v*co]);}
  const rect=(x,y,w,h)=>[[x,y],[x+w,y],[x+w,y+h],[x,y+h]];
  function intersect(a,b){for(const poly of [a,b])for(let i=0;i<4;i++){const p=poly[i],r=poly[(i+1)%4],axis=[p[1]-r[1],r[0]-p[0]],aa=a.map(([x,y])=>x*axis[0]+y*axis[1]),bb=b.map(([x,y])=>x*axis[0]+y*axis[1]);if(Math.max(...aa)<Math.min(...bb)||Math.max(...bb)<Math.min(...aa))return false;}return true;}
  function conflict(a,b,horizon){const dx=b.x-a.x,dy=b.y-a.y,vx=b.v*Math.cos(b.a)-a.v*Math.cos(a.a),vy=b.v*Math.sin(b.a)-a.v*Math.sin(a.a),vv=vx*vx+vy*vy,t=vv>1e-9?Math.max(0,Math.min(horizon,-(dx*vx+dy*vy)/vv)):0,ahead=dx*Math.cos(a.a)+dy*Math.sin(a.a);return ahead>-10&&Math.hypot(dx+vx*t,dy+vy*t)<45;}
  function snap(){const s=model.sim;return {tick:s.tick,ego:clone(s.ego),traffic:s.traffic.map(c=>({id:c.id,s:c.s,v:c.v,braking:c.braking})),status:s.status,contact:s.contact};}
  function record(type,extra={}){model.events.push({seq:model.events.length+1,type,...extra});}
  function tick(){if(!model.started||model.sim.status!=='driving'||model.submitting)return;const s=model.sim,e=s.ego,w=model.state.world,p=w.physics,[steer,pedal]=model.control;
    const targets=s.traffic.map(c=>{const a=pose(c);let brake=conflict(a,e,c.horizon);for(const other of s.traffic){if(other.id===c.id)continue;if(other.lane===c.lane){const gap=((other.s-c.s)%c.cycle+c.cycle)%c.cycle;if(gap>0&&gap<52+c.v*.8)brake=true;}else if(other.lane<c.lane&&conflict(a,pose(other),2.4))brake=true;}return brake;});
    e.v=q(Math.max(0,Math.min(p.max_speed,e.v+(pedal===1?p.acceleration:pedal===-1?-p.brake:-p.drag)*.02)));e.a=q(e.a+e.v/p.wheelbase*Math.tan(steer*p.steer_angle)*.02);e.x=q(e.x+e.v*Math.cos(e.a)*.02);e.y=q(e.y+e.v*Math.sin(e.a)*.02);
    s.traffic.forEach((c,i)=>{c.braking=targets[i];c.v=q(Math.max(0,Math.min(c.cruise,c.v+(c.braking?-c.decel:18)*.02)));c.s=q(c.s+c.v*.02);if(c.s>(c.lane<2?1150:770))c.s=q(c.s-c.cycle);});s.tick++;
    const body=corners(e),r=w.road_half,l=450-r,rr=450+r,t=260-r,b=260+r,lawns=[rect(-1000,-1000,l+1000,t+1000),rect(rr,-1000,2000,t+1000),rect(-1000,b,l+1000,2000),rect(rr,b,2000,2000)];
    for(const c of s.traffic)if(intersect(body,corners(pose(c)))){s.status='collision';s.contact=c.id;break;}
    if(s.status==='driving'&&(lawns.some(lawn=>intersect(body,lawn))||body.some(([x,y])=>x<0||x>900||y<0||y>520))){s.status='offroad';s.contact='road edge';}
    const g=w.goal;if(s.status==='driving'&&body.every(([x,y])=>x>=g.x&&x<=g.x+g.width&&y>=g.y&&y<=g.y+g.height))s.status='arrived';
    if(s.status==='driving'&&s.tick>=p.max_ticks)s.status='timeout';record('tick',{state:snap()});draw();update();
  }
  function pump(){if(!model.started||model.submitting)return;const target=Math.floor((performance.now()-model.startedAt)/20+1e-7);while(model.sim.tick<target&&model.sim.status==='driving')tick();}
  function frame(){pump();timer=requestAnimationFrame(frame);}
  function setControl(value,source){pump();if(!model.started||model.sim.status!=='driving'||model.submitting)return;if(value.every((v,i)=>v===model.control[i]))return;model.control=value;record('control',{tick:model.sim.tick,value:[...value],input_source:source});update();}
  function start(){if(model.started)return;model.started=true;model.startedAt=performance.now();record('start');document.getElementById('cj-start').disabled=true;model.helpers.setReadout('JUNCTION LIVE','idle');update();}
  async function submit(){pump();if(model.submitting||model.passed)return;const current=model;if(!current.started)start();record('submit',{tick:model.sim.tick});current.submitting=true;const payload={mechanic_id:'courtesy_junction',task_id:current.state.task_id,challenge_id:current.state.challenge_id,control_condition:current.state.control_condition,events:current.events,final:snap()};
    try{const response=await fetch('/result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('result service unavailable');const outcome=await response.json();if(outcome.passed){current.passed=true;current.helpers.setReadout('PASS','passed');document.getElementById('cj-verdict').innerHTML='<b>PASS</b><span>Delivery received. No contact.</span>';document.getElementById('cj-verdict').hidden=false;}else{current.nextState=outcome.state;current.helpers.setReadout('FAIL','error');document.getElementById('cj-verdict').innerHTML='<b>FAIL</b><span>Delivery not completed.</span>';document.getElementById('cj-verdict').hidden=false;document.getElementById('cj-retry').hidden=false;}}catch(e){current.events.pop();current.submitting=false;current.helpers.setReadout('Connection interrupted · submit again','error');}}
  function update(){const s=model.sim;document.querySelector('.courtesy-junction').dataset.status=s.status;document.getElementById('cj-speed').textContent=String(Math.round(s.ego.v));document.getElementById('cj-steer').textContent=['LEFT','CENTER','RIGHT'][model.control[0]+1];document.getElementById('cj-pedal').textContent=['BRAKE','COAST','THROTTLE'][model.control[1]+1];document.querySelectorAll('[data-axis]').forEach(b=>b.setAttribute('aria-pressed',String(model.control[Number(b.dataset.axis)]===Number(b.dataset.value))));if(s.status!=='driving'&&!model.submitting&&!model.passed){const v=document.getElementById('cj-verdict');v.hidden=false;v.innerHTML=s.status==='arrived'?'<b>DELIVERED</b><span>File the delivery to verify.</span>':`<b>STOP</b><span>${s.status==='collision'?'Vehicle contact':s.status==='offroad'?'Road edge crossed':'Delivery time expired'} · file this attempt to retry.</span>`;}}
  function path(ctx,poly){ctx.beginPath();poly.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();}
  function car(ctx,c,color,braking,ego=false){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.a);ctx.fillStyle='#142a30';for(const x of [-13,9])for(const y of [-11,8])ctx.fillRect(x,y,7,3);ctx.fillStyle=color;ctx.fillRect(-20,-11,40,22);ctx.strokeStyle='#24333d';ctx.lineWidth=1;ctx.strokeRect(-19.5,-10.5,39,21);ctx.fillStyle='#244959';ctx.fillRect(6,-8,6,16);ctx.fillStyle='rgba(255,255,255,.35)';ctx.fillRect(7,-7,2,14);ctx.fillStyle=braking?'#ff2929':'#864740';ctx.fillRect(-20,-9,3,5);ctx.fillRect(-20,4,3,5);ctx.fillStyle='#fff3bc';ctx.fillRect(18,-9,2,5);ctx.fillRect(18,4,2,5);if(ego){ctx.fillStyle='#fff4d5';ctx.fillRect(-10,-7,12,14);ctx.strokeStyle='#c49048';ctx.strokeRect(-10,-7,12,14);ctx.beginPath();ctx.moveTo(-4,-7);ctx.lineTo(-4,7);ctx.stroke();}ctx.restore();}
  function draw(){const ctx=document.getElementById('cj-canvas').getContext('2d'),w=model.state.world,r=w.road_half,l=450-r,rr=450+r,t=260-r,b=260+r;ctx.fillStyle='#b6cba9';ctx.fillRect(0,0,900,520);
    // Original model-town lawns and buildings stay outside the actual road collider.
    for(const [x,y,ww,hh] of [[25,24,l-55,t-48],[rr+30,24,850-rr,t-48],[25,b+28,l-55,460-b],[rr+30,b+28,850-rr,460-b]]){ctx.fillStyle='#a1ba97';ctx.fillRect(x,y,ww,hh);ctx.fillStyle='#d9d0b6';ctx.fillRect(x+18,y+16,ww-36,hh-30);ctx.fillStyle='#748d86';ctx.fillRect(x+26,y+24,ww-52,Math.max(14,hh-46));ctx.fillStyle='#d7e8df';for(let a=x+38;a<x+ww-25;a+=38)ctx.fillRect(a,y+32,20,12);}
    ctx.fillStyle='#e0d6b6';ctx.fillRect(l-8,0,r*2+16,520);ctx.fillRect(0,t-8,900,r*2+16);ctx.fillStyle='#52616a';ctx.fillRect(l,0,2*r,520);ctx.fillRect(0,t,900,2*r);
    ctx.strokeStyle='#e8d9ac';ctx.lineWidth=3;ctx.setLineDash([18,18]);ctx.beginPath();ctx.moveTo(450,0);ctx.lineTo(450,t);ctx.moveTo(450,b);ctx.lineTo(450,520);ctx.moveTo(0,260);ctx.lineTo(l,260);ctx.moveTo(rr,260);ctx.lineTo(900,260);ctx.stroke();ctx.setLineDash([]);
    ctx.strokeStyle='#d9e3db';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(459,b+13);ctx.lineTo(rr-8,b+13);ctx.stroke();
    const g=w.goal;ctx.fillStyle='#8fdac0';ctx.fillRect(g.x,g.y,g.width,g.height);ctx.strokeStyle='#eefce9';ctx.lineWidth=3;ctx.strokeRect(g.x,g.y,g.width,g.height);ctx.save();ctx.beginPath();ctx.rect(g.x,g.y,g.width,g.height);ctx.clip();ctx.strokeStyle='#47a392';ctx.lineWidth=10;for(let x=g.x-70;x<g.x+g.width+70;x+=25){ctx.beginPath();ctx.moveTo(x,g.y+g.height);ctx.lineTo(x+60,g.y);ctx.stroke();}ctx.restore();ctx.fillStyle='#fff8db';ctx.font='bold 16px sans-serif';ctx.textAlign='center';ctx.fillText(w.turn==='left'?'← DEPARTURE':'DEPARTURE →',w.turn==='left'?110:790,w.turn==='left'?157:375);
    for(const c of model.sim.traffic)car(ctx,pose(c),c.color,c.braking);car(ctx,model.sim.ego,'#f5c65c',model.control[1]===-1,true);
    if(model.sim.status==='collision'){const c=model.sim.ego;ctx.strokeStyle='#ff6262';ctx.lineWidth=4;path(ctx,corners(c));ctx.stroke();}
  }
  async function render(state,helpers){if(cleanup)cleanup();if(timer)cancelAnimationFrame(timer);document.body.dataset.mechanic='courtesy-junction';const mode=state.control_condition.interaction;model={state,helpers,sim:{ego:clone(state.world.start),traffic:clone(state.world.traffic),tick:0,status:'driving',contact:null},control:[0,0],events:[],started:false,submitting:false,passed:false};window.courtesyJunctionModel=model;
    const buttons=mode==='simplified'?`<div class="cj-buttons">${[['LEFT',0,-1],['CENTER',0,0],['RIGHT',0,1],['BRAKE',1,-1],['COAST',1,0],['THROTTLE',1,1]].map(([label,axis,value])=>`<button data-axis="${axis}" data-value="${value}">${label}</button>`).join('')}</div><p>Click to set steering and pedal.<br>Settings stay until changed.</p>`:'<div class="cj-keys"><span>↑<small>THROTTLE</small></span><div><span>←</span><span>↓<small>BRAKE</small></span><span>→</span></div></div><p>Hold arrows to drive and steer.<br>Release to center / coast.</p>';
    helpers.app.innerHTML=`<section class="courtesy-junction" data-interaction="${mode}" tabindex="0"><header><div><small>THE SMALL HOURS DELIVERY COMPANY</small><h1>Courtesy Junction</h1></div><div class="cj-badge">ONE PARCEL<br><b>NO DENTS.</b></div></header><main><div class="cj-scene"><canvas id="cj-canvas" width="900" height="520"></canvas><div id="cj-verdict" hidden></div></div><aside><h2>YOUR DELIVERY</h2><p class="cj-mission">Yellow car → striped road.<br>Stay on the road. No contact.</p><div class="cj-instrument"><b id="cj-speed">0</b><span>SPEED</span></div>${buttons}<div class="cj-state"><b id="cj-steer">CENTER</b><b id="cj-pedal">COAST</b></div><button id="cj-start">START ENGINE</button><button id="cj-retry" hidden>NEW DELIVERY</button></aside></main><footer><div><b>Drivers may yield. Watch them slow.</b><div class="readout" data-status="idle">READY AT THE JUNCTION</div></div><button id="cj-submit">FILE DELIVERY</button></footer></section>`;
    document.getElementById('cj-start').onclick=start;document.getElementById('cj-submit').onclick=submit;document.getElementById('cj-retry').onclick=()=>{if(model.nextState)render(model.nextState,helpers);};document.querySelectorAll('[data-axis]').forEach(b=>b.onclick=()=>{const v=[...model.control];v[Number(b.dataset.axis)]=Number(b.dataset.value);setControl(v,'panel_buttons');});
    const held=new Set(),keys=new Set(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown']);function key(e){if(mode!=='full'||!keys.has(e.key))return;e.preventDefault();if(e.type==='keydown')held.add(e.key);else held.delete(e.key);setControl([Number(held.has('ArrowRight'))-Number(held.has('ArrowLeft')),Number(held.has('ArrowUp'))-Number(held.has('ArrowDown'))],'held_keys');}function blur(){held.clear();if(mode==='full')setControl([0,0],'held_keys');}window.addEventListener('keydown',key);window.addEventListener('keyup',key);window.addEventListener('blur',blur);cleanup=()=>{window.removeEventListener('keydown',key);window.removeEventListener('keyup',key);window.removeEventListener('blur',blur);};timer=requestAnimationFrame(frame);draw();update();helpers.setReadout('READY AT THE JUNCTION','idle');
  }
  window.WeirdCaptchaMechanics=window.WeirdCaptchaMechanics||{};window.WeirdCaptchaMechanics.courtesy_junction={rootSelector:'.courtesy-junction',render};
})();
