(() => {
  "use strict";
  let model = null, raf = null;
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
  const round2 = (v) => Math.round(Number(v) * 100) / 100;
  const clean = (v) => String(v == null ? "" : v).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
  const distance = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1]);
  const now = () => Math.round(performance.now() - model.startedAt);
  function inputSource() { return model?.interaction === "simplified" ? "proxy_controls" : "direct_canvas"; }
  function record(kind, details = {}) { const source = kind === "playback_complete" ? {} : {input_source: inputSource()}; const item = {sequence: model.events.length + 1, kind, t_ms: now(), ...source, ...details}; model.events.push(item); return item; }
  function artifact() { return model.state.artifacts[model.current]; }
  function tokenMap() { return Object.fromEntries(artifact().stack.map((token) => [token.id, token])); }
  function point(event) { const rect = document.getElementById("restoration-canvas").getBoundingClientRect(); return [round2(clamp((event.clientX - rect.left) / rect.width * model.state.stage.width, 0, model.state.stage.width)), round2(clamp((event.clientY - rect.top) / rect.height * model.state.stage.height, 0, model.state.stage.height))]; }
  function inside(p, rect) { return p[0] >= rect.x && p[0] <= rect.x + rect.width && p[1] >= rect.y && p[1] <= rect.y + rect.height; }
  function format(token, inverse = false) {
    const value = inverse ? (token.kind === "rotate" || token.kind === "slice" ? -token.applied : token.kind === "scale" ? Math.round(10000 / token.applied) : 1) : token.applied;
    if (token.kind === "rotate") return `${value > 0 ? "↻" : "↺"}${Math.abs(value)}°`;
    if (token.kind === "slice") return `SPLIT ${value > 0 ? "+" : "−"}${Math.abs(value)}`;
    if (token.kind === "scale") return `SCALE ${Number(value / 100).toFixed(2)}`;
    return inverse ? "MIRROR ↶" : "MIRROR ↷";
  }
  function icon(token) { return token.kind === "rotate" ? "⟳" : token.kind === "slice" ? "≋" : token.kind === "scale" ? "↕" : "⇆"; }
  function arrangementCorrect() { const expected = [...artifact().stack].reverse().map((item) => item.id); return expected.every((id, index) => model.placements[index] === id && model.inverted.has(id)); }
  function workbenchReady() { const tokenIds = artifact().stack.map((item) => item.id); return Object.keys(model.placements).length === model.state.slots.length && tokenIds.every((id) => model.inverted.has(id)); }
  function presentation() { const parameters = model?.state?.control_condition?.difficulty_parameters || {}; return {template: parameters.show_inverse_template !== false, oracle: parameters.show_arrangement_oracle !== false}; }
  function gateWords(count) { return ["zero", "one", "two", "three", "four"][count] || String(count); }
  function gatePhrase(count) { return count === 1 ? "the one gate" : count === 2 ? "both gates" : `all ${gateWords(count)} gates`; }
  function canStartRail() { return presentation().oracle ? arrangementCorrect() : workbenchReady(); }

  function drawShape(context, kind, ink, transforms, at = [470, 130], size = 54) {
    context.save(); context.translate(at[0], at[1]); context.rotate(transforms.rotate * Math.PI / 180); context.scale(transforms.mirror, transforms.scale); context.strokeStyle = ink; context.fillStyle = `${ink}33`; context.lineWidth = 6; context.lineJoin = "round"; context.lineCap = "round";
    const path = () => {
      context.beginPath();
      if (kind === "gear") { for (let index = 0; index < 16; index += 1) { const a = index / 16 * Math.PI * 2, radius = index % 2 ? size * .72 : size; const x = Math.cos(a) * radius, y = Math.sin(a) * radius; if (!index) context.moveTo(x, y); else context.lineTo(x, y); } context.closePath(); context.moveTo(size * .24, 0); context.arc(0, 0, size * .24, 0, Math.PI * 2); }
      else if (kind === "signal_kite") { context.moveTo(0, -size); context.lineTo(size * .7, 0); context.lineTo(0, size); context.lineTo(-size * .7, 0); context.closePath(); context.moveTo(0, size); context.lineTo(size * .4, size * 1.35); context.moveTo(0, size); context.lineTo(-size * .35, size * 1.55); }
      else { context.arc(-size * .45, 0, size * .42, 0, Math.PI * 2); context.moveTo(-size * .03, 0); context.lineTo(size, 0); context.lineTo(size, size * .38); context.moveTo(size * .58, 0); context.lineTo(size * .58, -size * .34); }
    };
    if (transforms.slice) { context.save(); context.beginPath(); context.rect(-size * 2, -size * 2, size * 4, size * 2); context.clip(); context.translate(transforms.slice / 2, 0); path(); context.fill(); context.stroke(); context.restore(); context.save(); context.beginPath(); context.rect(-size * 2, 0, size * 4, size * 2); context.clip(); context.translate(-transforms.slice / 2, 0); path(); context.fill(); context.stroke(); context.restore(); }
    else { path(); context.fill(); context.stroke(); }
    context.restore();
  }
  function transformAt(progress) {
    const result = {rotate: 0, scale: 1, mirror: 1, slice: 0};
    artifact().stack.forEach((token, index) => { const amount = clamp(progress * artifact().stack.length - index, 0, 1); if (token.kind === "rotate") result.rotate += token.applied * amount; else if (token.kind === "scale") result.scale *= 1 + (token.applied / 100 - 1) * amount; else if (token.kind === "mirror") result.mirror *= 1 - 2 * amount; else result.slice += token.applied * amount; }); return result;
  }
  function drawToken(context, token, rect, inverse, placed) {
    context.save(); context.fillStyle = placed ? "rgba(16,38,45,.94)" : "rgba(11,28,35,.88)"; context.strokeStyle = inverse ? "#75e4c8" : "#d6ba65"; context.lineWidth = inverse ? 3 : 1.5; context.fillRect(rect.x, rect.y, rect.width, rect.height); context.strokeRect(rect.x, rect.y, rect.width, rect.height); context.fillStyle = inverse ? "#9ff0da" : "#e8d58c"; context.font = "900 15px Georgia"; context.textAlign = "left"; context.fillText(icon(token), rect.x + 12, rect.y + 22); context.font = "900 9px Courier New"; context.fillText(format(token, inverse), rect.x + 39, rect.y + 21); context.fillStyle = "rgba(197,217,211,.58)"; context.font = "800 7px Courier New"; context.fillText(placed ? "INVERSE SWITCH" : "DRAG MODULE", rect.x + 39, rect.y + 40); if (placed) { context.beginPath(); context.arc(rect.x + rect.width - 15, rect.y + 15, 10, 0, Math.PI * 2); context.fillStyle = inverse ? "#62d9b9" : "#5b4d31"; context.fill(); context.fillStyle = inverse ? "#072018" : "#ead887"; context.font = "900 11px Courier New"; context.textAlign = "center"; context.fillText("↶", rect.x + rect.width - 15, rect.y + 19); } context.restore();
  }
  function drawFrame() {
    if (!model) return; const canvas = document.getElementById("restoration-canvas"), context = canvas?.getContext("2d"); if (!canvas || !context) return; const art = model.current < model.state.artifacts.length ? artifact() : model.state.artifacts[model.state.artifacts.length - 1];
    const gradient = context.createLinearGradient(0, 0, 0, canvas.height); gradient.addColorStop(0, "#0d2028"); gradient.addColorStop(1, "#071216"); context.fillStyle = gradient; context.fillRect(0, 0, canvas.width, canvas.height); context.strokeStyle = "rgba(108,187,185,.09)"; for (let x = 0; x <= canvas.width; x += 32) { context.beginPath(); context.moveTo(x, 0); context.lineTo(x, canvas.height); context.stroke(); } for (let y = 0; y <= canvas.height; y += 32) { context.beginPath(); context.moveTo(0, y); context.lineTo(canvas.width, y); context.stroke(); }
    if (model.phase === "playback") {
      const elapsed = performance.now() - model.playbackStartedAt, progress = clamp(elapsed / art.playback_ms, 0, 1), stage = Math.min(art.stack.length - 1, Math.floor(progress * art.stack.length)); context.fillStyle = "rgba(7,14,17,.78)"; context.fillRect(125, 45, 690, 190); context.strokeStyle = "rgba(229,205,116,.36)"; context.strokeRect(125, 45, 690, 190); drawShape(context, art.kind, art.ink, transformAt(progress), [470, 135], 47);
      art.stack.forEach((token, index) => { const x = art.stack.length === 3 ? 246 + index * 225 : 470 + (index - (art.stack.length - 1) / 2) * 190; context.fillStyle = index === stage ? "#f0d778" : "rgba(166,194,189,.42)"; context.font = "900 10px Courier New"; context.textAlign = "center"; context.fillText(`${index + 1} / ${format(token, false)}`, x, 215); });
      context.fillStyle = "rgba(231,220,172,.8)"; context.font = "900 9px Courier New"; context.textAlign = "left"; context.fillText("TRANSFORMATION FILM / DO NOT BLINK", 145, 68);
      if (progress >= 1 && !model.playbackClosed) { model.playbackClosed = true; record("playback_complete", {artifact_id: art.id, duration_ms: Math.round(elapsed)}); model.phase = "work"; model.helpers.setReadout("FILM SHUTTERED / BUILD THE INVERSE", "idle"); update(); }
    } else if (model.current < model.state.artifacts.length) {
      context.fillStyle = "rgba(226,216,164,.64)"; context.font = "900 8px Courier New"; context.textAlign = "left"; context.fillText("CORRUPTED SPECIMEN", 40, 36); drawShape(context, art.kind, art.ink, transformAt(1), [128, 112], 34);
      context.fillStyle = "rgba(126,185,182,.65)"; context.fillText("MODULE RACK", 205, 219); const map = tokenMap(); art.rack_rects.forEach((rect) => { if (!Object.values(model.placements).includes(rect.token_id)) drawToken(context, map[rect.token_id], rect, model.inverted.has(rect.token_id), false); });
      model.state.slots.forEach((slot) => { context.fillStyle = "rgba(5,13,17,.72)"; context.strokeStyle = "rgba(125,194,188,.28)"; context.lineWidth = 1; context.fillRect(slot.x, slot.y, slot.width, slot.height); context.strokeRect(slot.x, slot.y, slot.width, slot.height); context.fillStyle = "rgba(154,194,189,.52)"; context.font = "900 8px Courier New"; context.textAlign = "left"; context.fillText(`INVERSE ${slot.index + 1}`, slot.x + 8, slot.y - 8); const tokenId = model.placements[slot.index]; if (tokenId) drawToken(context, map[tokenId], slot, model.inverted.has(tokenId), true); });
      const rail = model.state.rail; context.beginPath(); context.moveTo(rail.start[0], rail.start[1]); context.lineTo(rail.end[0], rail.end[1]); context.strokeStyle = presentation().oracle && arrangementCorrect() ? "#65dcbf" : "rgba(218,192,104,.42)"; context.lineWidth = 5; context.stroke(); rail.gate_x.forEach((x, index) => { context.fillStyle = model.railHold?.gates > index ? "#61d9ba" : "#192d32"; context.strokeStyle = "#c6aa5b"; context.lineWidth = 2; context.fillRect(x - 8, rail.start[1] - 33, 16, 66); context.strokeRect(x - 8, rail.start[1] - 33, 16, 66); }); drawShape(context, art.kind, art.ink, {rotate: 0, scale: .42, mirror: 1, slice: 0}, model.railHold ? model.railHold.point : rail.start, 27);
      if (model.drag) { const token = map[model.drag.tokenId], rect = {x: model.drag.point[0] - 75, y: model.drag.point[1] - 28, width: 150, height: 56}; context.globalAlpha = .76; drawToken(context, token, rect, model.inverted.has(token.id), false); context.globalAlpha = 1; }
    } else { context.fillStyle = "#6de0bf"; context.font = "900 30px Georgia"; context.textAlign = "center"; context.fillText(`${model.state.artifacts.length} SPECIMEN${model.state.artifacts.length === 1 ? "" : "S"} RESTORED`, canvas.width / 2, canvas.height / 2); }
    raf = requestAnimationFrame(drawFrame);
  }
  function startPlayback() { model.phase = "playback"; model.playbackStartedAt = performance.now(); model.playbackClosed = false; model.placements = {}; model.inverted = new Set(); model.drag = null; model.railHold = null; model.proxyTokenId = null; model.helpers.setReadout("TRANSFORMATION FILM RUNNING", "pending"); update(); }
  function updateProxyControls() {
    const panel = document.getElementById("restoration-proxy-controls");
    if (!panel || model?.interaction !== "simplified") return;
    if (model.current >= model.state.artifacts.length) { panel.innerHTML = "<b>ALL SPECIMENS RESTORED</b>"; return; }
    const art = artifact(), map = tokenMap(), work = model.phase === "work";
    const available = art.rack_rects.filter((rect) => !Object.values(model.placements).includes(rect.token_id));
    const selected = model.proxyTokenId && available.some((rect) => rect.token_id === model.proxyTokenId) ? model.proxyTokenId : null;
    if (!selected) model.proxyTokenId = null;
    const modules = available.map((rect) => `<button type="button" data-proxy-action="select" data-token-id="${clean(rect.token_id)}" ${work && !model.railHold ? "" : "disabled"}>${clean(format(map[rect.token_id], false))}${selected === rect.token_id ? " · SELECTED" : ""}</button>`).join("");
    const slots = model.state.slots.map((slot) => `<button type="button" data-proxy-action="place" data-slot-index="${slot.index}" ${work && !model.railHold && selected && model.placements[slot.index] == null ? "" : "disabled"}>PLACE INVERSE ${slot.index + 1}</button>`).join("");
    const switches = model.state.slots.map((slot) => { const tokenId = model.placements[slot.index]; return tokenId ? `<button type="button" data-proxy-action="invert" data-token-id="${clean(tokenId)}" ${work && !model.railHold ? "" : "disabled"}>${model.inverted.has(tokenId) ? "INVERSE SET" : `INVERT ${clean(format(map[tokenId], false))}`}</button>` : ""; }).join("");
    const hold = model.railHold, minimum = model.state.requirements.minimum_rail_samples;
    const rail = !hold ? `<button type="button" data-proxy-action="rail-start" ${work && workbenchReady() ? "" : "disabled"}>START RESTORATION HOLD</button>` : `<div class="restoration-proxy-group restoration-proxy-rail"><i>RESTORATION HOLD / ${hold.samples}/${minimum} SAMPLES</i><button type="button" data-proxy-action="rail-advance">ADVANCE THROUGH RAIL</button><button type="button" data-proxy-action="rail-end">END RAIL HOLD</button></div>`;
    panel.innerHTML = `<div class="restoration-proxy-group"><i>MODULE PROXIES</i>${modules || "<b>ALL MODULES PLACED</b>"}</div><div class="restoration-proxy-group"><i>INVERSE RACK</i>${slots}</div><div class="restoration-proxy-group"><i>SWITCHES</i>${switches || "<b>PLACE MODULES FIRST</b>"}</div>${rail}`;
  }
  function update() { if (!model) return; const total = model.state.artifacts.length, root = document.querySelector(".restoration-press"), showOracle = presentation().oracle; root.dataset.phase = model.phase; root.dataset.round = String(model.current); root.dataset.completed = String(model.current === total); root.dataset.arranged = String(showOracle && model.current < total && arrangementCorrect()); document.getElementById("restoration-round").textContent = `${Math.min(model.current + 1, total)}/${total}`; document.getElementById("restoration-phase").textContent = model.current === total ? "SEALED" : model.phase === "playback" ? "FILM" : "PRESS"; document.getElementById("restoration-status").textContent = model.current === total ? "RESTORATION LOG COMPLETE" : model.phase === "playback" ? "WATCH THE STACK CHANGE IN ORDER" : showOracle && arrangementCorrect() ? (model.interaction === "simplified" ? "INVERSE STACK READY — START RESTORATION HOLD" : "INVERSE STACK READY — HOLD SPECIMEN THROUGH RAIL") : "REVERSE THE FILM · SWITCH EACH MODULE TO INVERSE"; const replay = document.getElementById("restoration-replay"); if (replay && model.current < total) replay.disabled = model.phase !== "work" || model.replayUsed[model.current] >= artifact().replay_limit; updateProxyControls(); }
  function hitRack(p) { if (model.phase !== "work") return null; return artifact().rack_rects.find((rect) => !Object.values(model.placements).includes(rect.token_id) && inside(p, rect)) || null; }
  function hitInvert(p) { for (const slot of model.state.slots) { const tokenId = model.placements[slot.index]; if (tokenId && distance(p, [slot.x + slot.width - 15, slot.y + 15]) <= 14) return tokenId; } return null; }
  function finishRail(p, releaseTarget = null, pointerId = null) {
    const hold = model.railHold, rail = model.state.rail, duration = Math.round(performance.now() - hold.startedAt), accepted = hold.samples >= model.state.requirements.minimum_rail_samples && duration >= model.state.requirements.minimum_rail_ms && hold.gates === rail.gate_x.length && distance(p, rail.end) <= 30;
    record("rail_end", {point: p, duration_ms: duration, accepted}); model.railSamples += hold.samples; model.railHold = null; releaseTarget?.releasePointerCapture?.(pointerId);
    if (accepted) { model.completed.push(artifact().id); model.current += 1; model.proxyTokenId = null; model.helpers.setReadout("SPECIMEN RESTORED", "idle"); if (model.current < model.state.artifacts.length) startPlayback(); else { model.phase = "terminal"; update(); } }
    else { model.helpers.setReadout("RESTORATION RAIL INCOMPLETE", "error"); update(); }
  }
  function pointerDown(event) {
    if (!model || model.interaction !== "full" || model.phase !== "work" || model.drag || model.railHold || model.submitting || model.terminal) return; const p = point(event), invertId = hitInvert(p); if (invertId) { const before = model.inverted.has(invertId), after = !before; record("invert", {token_id: invertId, before, after}); if (after) model.inverted.add(invertId); else model.inverted.delete(invertId); model.helpers.setReadout(after ? "MODULE SET TO INVERSE" : "MODULE RETURNED TO FORWARD", "idle"); update(); return; }
    const rack = hitRack(p); if (rack) { record("chip_down", {token_id: rack.token_id, point: p}); model.drag = {pointerId: event.pointerId, tokenId: rack.token_id, startedAt: performance.now(), point: p}; event.currentTarget.setPointerCapture?.(event.pointerId); return; }
    if (canStartRail() && distance(p, model.state.rail.start) <= 28) { record("rail_start", {point: p}); model.railHold = {pointerId: event.pointerId, startedAt: performance.now(), samples: 0, gates: 0, point: p}; event.currentTarget.setPointerCapture?.(event.pointerId); model.helpers.setReadout("CONTINUOUS RESTORATION CONTACT", "pending"); }
  }
  function pointerMove(event) { const p = point(event); if (model?.drag && model.drag.pointerId === event.pointerId) { if (distance(p, model.drag.point) < 3) return; model.drag.point = p; record("chip_move", {token_id: model.drag.tokenId, point: p, elapsed_ms: Math.round(performance.now() - model.drag.startedAt)}); } else if (model?.railHold && model.railHold.pointerId === event.pointerId) { const rail = model.state.rail; if (Math.abs(p[1] - rail.start[1]) > rail.half_height || p[0] + 2 < model.railHold.point[0]) { model.helpers.setReadout("PRESS CONTACT BROKEN / RESET WORKBENCH", "error"); return; } if (distance(p, model.railHold.point) < 3) return; model.railHold.point = p; model.railHold.samples += 1; while (model.railHold.gates < rail.gate_x.length && p[0] >= rail.gate_x[model.railHold.gates]) model.railHold.gates += 1; record("rail_sample", {point: p, elapsed_ms: Math.round(performance.now() - model.railHold.startedAt)}); } }
  function pointerUp(event, cancelled = false) {
    const p = point(event); if (model?.drag && model.drag.pointerId === event.pointerId) { const drag = model.drag, slot = model.state.slots.find((item) => inside(p, item)), accepted = !cancelled && Boolean(slot) && model.placements[slot.index] == null; record("chip_up", {token_id: drag.tokenId, point: p, duration_ms: Math.round(performance.now() - drag.startedAt), slot_index: slot ? slot.index : null, accepted, cancelled}); if (accepted) model.placements[slot.index] = drag.tokenId; model.drag = null; try { event.currentTarget.releasePointerCapture?.(event.pointerId); } catch (_) {} update(); return; }
    if (model?.railHold && model.railHold.pointerId === event.pointerId) { if (cancelled) { record("rail_cancel", {point: p}); model.railHold = null; model.helpers.setReadout("RESTORATION RAIL INCOMPLETE", "error"); try { event.currentTarget.releasePointerCapture?.(event.pointerId); } catch (_) {} update(); } else finishRail(p, event.currentTarget, event.pointerId); }
  }
  function replay() { if (!model || model.phase !== "work" || model.current >= model.state.artifacts.length || model.replayUsed[model.current] >= artifact().replay_limit) return; record("replay", {artifact_id: artifact().id}); model.replayUsed[model.current] += 1; model.replayCount += 1; startPlayback(); }
  function resetWork() { if (!model || model.phase !== "work" || model.drag || model.railHold) return; record("reset_work"); model.placements = {}; model.inverted = new Set(); model.resetCount += 1; model.helpers.setReadout("WORKBENCH CLEARED / FILM MEMORY RETAINED", "idle"); update(); }
  function proxyClick(event) {
    const button = event.target.closest("button[data-proxy-action]"); if (!button || !model || model.interaction !== "simplified" || model.phase !== "work" || model.submitting || model.terminal) return;
    const action = button.dataset.proxyAction;
    if (action === "select") { const tokenId = String(button.dataset.tokenId || ""); if (!model.railHold && artifact().rack_rects.some((rect) => rect.token_id === tokenId && !Object.values(model.placements).includes(tokenId))) { model.proxyTokenId = tokenId; model.helpers.setReadout("MODULE SELECTED / CHOOSE ITS INVERSE SLOT", "idle"); update(); } return; }
    if (action === "place") { const slotIndex = Number(button.dataset.slotIndex), tokenId = model.proxyTokenId; if (model.railHold || !Number.isInteger(slotIndex) || !tokenId || model.placements[slotIndex] != null) return; record("proxy_place", {token_id: tokenId, slot_index: slotIndex}); model.placements[slotIndex] = tokenId; model.proxyTokenId = null; model.helpers.setReadout("MODULE PLACED / SWITCH IT TO INVERSE", "idle"); update(); return; }
    if (action === "invert") { const tokenId = String(button.dataset.tokenId || ""), before = model.inverted.has(tokenId), after = !before; if (!Object.values(model.placements).includes(tokenId) || model.railHold) return; record("invert", {token_id: tokenId, before, after}); if (after) model.inverted.add(tokenId); else model.inverted.delete(tokenId); model.helpers.setReadout(after ? "MODULE SET TO INVERSE" : "MODULE RETURNED TO FORWARD", "idle"); update(); return; }
    if (action === "rail-start" && canStartRail()) { const start = [...model.state.rail.start]; record("rail_start", {point: start}); model.railHold = {startedAt: performance.now(), samples: 0, gates: 0, point: start}; model.helpers.setReadout("CONTINUOUS RESTORATION CONTACT", "pending"); update(); return; }
    if (action === "rail-advance" && model.railHold) { const hold = model.railHold, rail = model.state.rail, total = model.state.requirements.minimum_rail_samples, index = Math.min(total, hold.samples + 1), amount = index / total, p = [round2(rail.start[0] + (rail.end[0] - rail.start[0]) * amount), rail.start[1]]; hold.point = p; hold.samples += 1; while (hold.gates < rail.gate_x.length && p[0] >= rail.gate_x[hold.gates]) hold.gates += 1; record("rail_sample", {point: p, elapsed_ms: Math.round(performance.now() - hold.startedAt)}); update(); return; }
    if (action === "rail-end" && model.railHold) finishRail([...model.railHold.point]);
  }
  function payload() { return {mechanic_id: model.state.mechanic_id, task_id: model.state.task_id, challenge_id: model.state.challenge_id, interaction_mode: model.interaction, events: model.events, completed_ids: [...model.completed], replay_count: model.replayCount, reset_count: model.resetCount, rail_samples: model.railSamples, seal_count: model.sealCount, completed: model.current === model.state.artifacts.length}; }
  async function submit() { if (!model || model.drag || model.railHold || model.submitting || model.terminal) return; record("seal"); model.sealCount += 1; const current = model; current.submitting = true; current.helpers.setReadout("REPLAYING FILM, MODULE ORDER, AND CONTINUOUS PRESS…", "pending"); try { const response = await fetch("/result", {method: "POST", headers: {"content-type": "application/json"}, body: JSON.stringify(payload())}); const outcome = await response.json(); if (outcome.passed === true) { current.terminal = true; current.helpers.setReadout("PASS", "passed"); const verdict = document.querySelector(".restoration-verdict"); if (verdict) verdict.innerHTML = `<b>PASS</b><span>${current.state.artifacts.length} INVERSE STACK${current.state.artifacts.length === 1 ? "" : "S"} VERIFIED</span>`; document.querySelector(".restoration-press")?.setAttribute("data-verdict", "pass"); } else if (outcome.passed === false && outcome.state) { const helpers = current.helpers; await render(outcome.state, helpers, {freshFailure: true}); model.helpers.setReadout("FAIL", "error"); } else { current.submitting = false; current.helpers.setReadout("RESTORATION LOG REJECTED", "error"); } } catch (_error) { if (model === current) { current.submitting = false; current.helpers.setReadout("PRESS VERIFIER OFFLINE", "error"); } } }
  async function render(state, helpers, options = {}) {
    const interaction = state.control_condition?.interaction || "full", moduleCount = state.artifacts[0]?.stack?.length || 3, filmOrder = Array.from({length: moduleCount}, (_item, index) => index + 1).join(" → "), pressOrder = Array.from({length: moduleCount}, (_item, index) => moduleCount - index).join(" → "), parameters = state.control_condition?.difficulty_parameters || {}, showInverseTemplate = parameters.show_inverse_template !== false, gates = state.rail.gate_x.length, railGatePhrase = gatePhrase(gates);
    const instructions = interaction === "full" ? `<p>Drag modules into the inverse rack. Tap each corner switch, then hold the specimen through ${railGatePhrase}.</p>` : `<p>Select visible modules and their inverse slots here. Set every inverse switch, then start a restoration hold, advance through ${railGatePhrase}, and end the hold without breaking contact.</p><div id="restoration-proxy-controls" class="restoration-proxy-controls"></div>`;
    const pressCard = showInverseTemplate ? `<div class="stack-diagram"><i>FILM</i><b>${filmOrder}</b><i>PRESS</i><b>${pressOrder}</b></div>` : "<div class=\"stack-diagram\"><i>FILM</i><b>SHUTTERED ORDER</b><i>PRESS</i><b>RECALL WHAT CHANGED</b></div>";
    if (raf) cancelAnimationFrame(raf); document.body.dataset.mechanic = "restoration-press"; document.body.dataset.cheatMode = helpers.isCheatMode() ? "true" : "false"; model = {state, helpers, interaction, startedAt: performance.now(), events: [], current: 0, phase: "standby", playbackStartedAt: performance.now(), playbackClosed: false, placements: {}, inverted: new Set(), drag: null, railHold: null, proxyTokenId: null, completed: [], replayUsed: state.artifacts.map(() => 0), replayCount: 0, resetCount: 0, railSamples: 0, sealCount: 0, submitting: false, terminal: false}; window.modifierRestorationModel = model;
    helpers.app.innerHTML = `<section class="restoration-press" data-interaction="${clean(interaction)}" data-fresh-failure="${options.freshFailure ? "true" : "false"}" data-verdict=""><div class="restoration-verdict"><b>${options.freshFailure ? "FAIL" : ""}</b><span>${options.freshFailure ? "FRESH FILM THREADED" : ""}</span></div><header class="restoration-head"><div><span>KINETIC RESTORATION PRESS / ${clean(state.challenge_id)}</span><h1>${clean(state.prompt)}</h1></div><div class="restoration-index"><span>SPECIMEN</span><b id="restoration-round">1/${state.artifacts.length}</b><i id="restoration-phase">FILM</i></div></header><main class="restoration-main"><section class="restoration-stage"><canvas id="restoration-canvas" width="${state.stage.width}" height="${state.stage.height}"></canvas></section><aside class="restoration-console"><span>PRESS CARD</span><h2>Last damage.<br>First repair.</h2>${pressCard}${instructions}<button id="restoration-replay">REPLAY CURRENT FILM</button><button id="restoration-reset">CLEAR WORKBENCH</button></aside></main><footer class="restoration-foot"><div><span id="restoration-status">WATCH THE STACK CHANGE IN ORDER</span><div class="readout" data-status="idle">TRANSFORMATION FILM RUNNING</div></div><button id="restoration-submit">${clean(state.submit_label)}</button></footer>${helpers.cheatPanelTemplate()}</section>`;
    const canvas = document.getElementById("restoration-canvas"); canvas.addEventListener("pointerdown", pointerDown); canvas.addEventListener("pointermove", pointerMove); canvas.addEventListener("pointerup", event => pointerUp(event)); canvas.addEventListener("pointercancel", event => pointerUp(event, true)); canvas.addEventListener("lostpointercapture", event => pointerUp(event, true)); document.getElementById("restoration-proxy-controls")?.addEventListener("click", proxyClick); document.getElementById("restoration-replay").addEventListener("click", replay); document.getElementById("restoration-reset").addEventListener("click", resetWork); document.getElementById("restoration-submit").addEventListener("click", submit); helpers.installCheatPanel(); startPlayback(); raf = requestAnimationFrame(drawFrame); if (options.freshFailure) { const current = model; setTimeout(() => document.querySelector(".restoration-press")?.setAttribute("data-fresh-failure", "false"), 1350); }
  }
  window.WeirdCaptchaMechanics = window.WeirdCaptchaMechanics || {};
  window.WeirdCaptchaMechanics.modifier_stack_image_grid = {rootSelector: ".restoration-press", render};
})();
