(()=>{'use strict';
const ID='porcelain_turntable';let cleanup;
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1],sub=(a,b)=>[a[0]-b[0],a[1]-b[1]],cross=(a,b)=>a[0]*b[1]-a[1]*b[0],point=(a,b,t)=>[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t];
function closest(a,b,c,d){const ab=sub(b,a),cd=sub(d,c),den=cross(ab,cd);if(Math.abs(den)>1e-12){const ac=sub(c,a),t=cross(ac,cd)/den,u=cross(ac,ab)/den;if(t>=0&&t<=1&&u>=0&&u<=1)return[point(a,b,t),point(c,d,u),t];}const candidates=[];for(const[v,t]of[[a,0],[b,1]]){const u=Math.max(0,Math.min(1,dot(sub(v,c),cd)/Math.max(dot(cd,cd),1e-12))),w=point(c,d,u);candidates.push([dot(sub(v,w),sub(v,w)),v,w,t]);}for(const w of[c,d]){const t=Math.max(0,Math.min(1,dot(sub(w,a),ab)/Math.max(dot(ab,ab),1e-12))),v=point(a,b,t);candidates.push([dot(sub(v,w),sub(v,w)),v,w,t]);}candidates.sort((a,b)=>a[0]-b[0]);return candidates[0].slice(1);}
function geometry(s,p){const[a,b]=s,base=[-p.base_distance,0],elbow=[base[0]+p.l1*Math.cos(a),p.l1*Math.sin(a)],tip=[elbow[0]+p.l2*Math.cos(a+b),elbow[1]+p.l2*Math.sin(a+b)],petals=[0,1,2].map(i=>[p.radius*Math.cos(s[2]+i*2*Math.PI/3),p.radius*Math.sin(s[2]+i*2*Math.PI/3)]);return[base,elbow,tip,petals];}
function step(s,u,p){s=[...s];let contacts=0;const dt=.002;for(let k=0;k<5;k++){const[a,b,theta]=s;let[va,vb,w]=s.slice(3);const l1=p.l1,l2=p.l2,m1=1,m2=.7,h=m2*l1*l2/2,d22=m2*l2*l2/3,d12=d22+h*Math.cos(b),d11=m1*l1*l1/3+m2*l1*l1+d22+2*h*Math.cos(b),det=d11*d22-d12*d12,inv00=d22/det,inv01=-d12/det,inv11=d11/det,r1=u[0]*p.torque-p.joint_damping*va+h*Math.sin(b)*(2*va*vb+vb*vb),r2=u[1]*p.torque-p.joint_damping*vb-h*Math.sin(b)*va*va;
va+=dt*(inv00*r1+inv01*r2);vb+=dt*(inv01*r1+inv11*r2);w*=Math.exp(-p.hinge_damping*dt/p.spinner_inertia);
const[base,elbow,tip,petals]=geometry(s,p);for(const[index,[aa,bb]]of[[base,elbow],[elbow,tip]].entries())for(const end of petals){const[v,z]=closest(aa,bb,[0,0],end),delta=sub(v,z),dist=Math.hypot(...delta),depth=p.finger_radius+p.petal_radius-dist;if(depth<=0)continue;let n=[delta[0]/Math.max(dist,1e-12),delta[1]/Math.max(dist,1e-12)];if(dist<1e-9)n=[0,1];const j0=cross(sub(v,base),n),j1=index?cross(sub(v,elbow),n):0,js=-cross(z,n),effective=j0*(inv00*j0+inv01*j1)+j1*(inv01*j0+inv11*j1)+js*js/p.spinner_inertia,rel=j0*va+j1*vb+js*w,impulse=Math.max(0,(.16*Math.max(0,depth-.0005)/dt-rel)/Math.max(effective,1e-12));va+=(inv00*j0+inv01*j1)*impulse;vb+=(inv01*j0+inv11*j1)*impulse;w+=js*impulse/p.spinner_inertia;if(impulse>1e-8)contacts++;}
s=[a+dt*va,b+dt*vb,theta+dt*w,va,vb,w];}return[s,contacts];}
const error=(s,p)=>Math.abs(Math.atan2(Math.sin(s[2]-p.target),Math.cos(s[2]-p.target))),settled=(s,u,p)=>u[0]===0&&u[1]===0&&error(s,p)<=p.tolerance&&Math.abs(s[5])<=p.settle_speed;
// Read-only physics access for oracle wiring tests. No privileged task actions.
window.PorcelainPhysics={step,geometry,error,settled};
async function render(state,helpers,fresh=false){if(cleanup)cleanup();document.body.dataset.mechanic=ID;const p=state.physics,full=(state.control_condition?.interaction||'full')==='full',m={s:[...state.initial],u:[0,0],tick:0,hold:0,contacts:0,events:[],running:false,finished:false,busy:false,startTime:0};window.porcelainModel=m;
helpers.app.innerHTML=`<section class="porcelain" data-challenge-id="${state.challenge_id}"><header><div><small>ATELIER / CONTACT STUDY 05</small><h1>Porcelain Turntable</h1></div><span class="pt-seal">FREE HINGE<br>NO MOTOR</span></header><div class="pt-layout"><div class="pt-stage"><canvas width="880" height="500" aria-label="Brass two-joint finger beside an unpowered porcelain spinner"></canvas><div class="pt-verdict" hidden><b></b><span></span></div></div><aside><small>THE SETTLING TEST</small><h2>One painted petal.<br>One quiet landing.</h2><p>Push the porcelain with the brass finger. Release both joints with the painted tip in the mint sector.</p><div class="pt-meter"><span>SPINNER SPEED</span><strong id="pt-speed">0.00 rad/s</strong><small>Settle below ${p.settle_speed.toFixed(2)} rad/s</small><div id="pt-progress"></div></div><div class="pt-joints">${[0,1].map((j)=>`<label>${j?'ELBOW':'SHOULDER'} <b id="pt-u${j}">○</b></label><div class="pt-controls">${[-1,0,1].map(u=>`<button data-j="${j}" data-u="${u}" ${full?'disabled':''}>${u<0?'↶':u>0?'↷':'○'}<small>${full?(u===0?'RELEASE':j?(u<0?'HOLD J':'HOLD L'):(u<0?'HOLD A':'HOLD D')):u<0?'SET −':u>0?'SET +':'SET 0'}</small></button>`).join('')}</div>`).join('')}</div><p class="pt-hint">${full?'Hold A / D for shoulder and J / L for elbow. Release to coast.':'Click to latch each joint torque. Set both to zero to coast.'}</p><button id="pt-start">BEGIN STUDY</button></aside></div><footer><div class="readout" data-status="idle">READY · PETAL MUST REST IN THE MINT SECTOR</div><button id="pt-submit">CERTIFY REST</button></footer></section>`;
const $=s=>helpers.app.querySelector(s),canvas=$('canvas'),ctx=canvas.getContext('2d'),keys=new Set();let frame;
const record=(type,more={})=>m.events.push({seq:m.events.length+1,tick:m.tick,type,...more});
const xy=v=>[570+v[0]*124,255+v[1]*100]; // replaced below by uniform physical scale
function pos(v){return[565+v[0]*105,250+v[1]*105];}
function line(a,b,r,color){a=pos(a);b=pos(b);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.lineWidth=r*210;ctx.lineCap='round';ctx.strokeStyle=color;ctx.stroke();}
function circle(v,r,color){ctx.beginPath();ctx.arc(...pos(v),r*105,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function paint(){ctx.clearRect(0,0,880,500);ctx.fillStyle='#132d32';ctx.fillRect(0,0,880,500);ctx.strokeStyle='#244248';ctx.lineWidth=1;for(let x=20;x<880;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,500);ctx.stroke();}for(let y=10;y<500;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(880,y);ctx.stroke();}
ctx.beginPath();ctx.arc(565,250,113,0,2*Math.PI);ctx.fillStyle='#193b41';ctx.fill();ctx.strokeStyle='#54767a';ctx.stroke();ctx.beginPath();ctx.arc(565,250,113,p.target-p.tolerance,p.target+p.tolerance);ctx.lineWidth=16;ctx.strokeStyle='#9cf2c6';ctx.stroke();
const[base,elbow,tip,petals]=geometry(m.s,p);for(let i=0;i<3;i++){line([0,0],petals[i],p.petal_radius,'#e9e4d6');line([0,0],petals[i],p.petal_radius*.65,i===0?'#478bc1':'#fcf8e9');}circle([0,0],.12,'#b58e50');circle([0,0],.045,'#233f46');
for(const[a,b]of[[base,elbow],[elbow,tip]]){line(a,b,p.finger_radius,'#b58c49');line(a,b,p.finger_radius*.55,'#f4d48e');}circle(base,.13,'#b5a181');circle(base,.055,'#233c40');circle(elbow,.10,'#e5c580');circle(elbow,.04,'#233c40');circle(tip,p.finger_radius,'#f4d48e');
ctx.font='13px sans-serif';ctx.fillStyle='#a9c0bd';ctx.fillText('TWO POWERED JOINTS',45,40);ctx.fillText('UNPOWERED PORCELAIN',575,40);ctx.fillText(`SECTOR ±${Math.round(p.tolerance*180/Math.PI)}°  ·  RELEASE & REST 0.8 s`,440,460);ctx.fillText(`STUDY TIME ${(m.tick/100).toFixed(1)} / 300 s`,40,460);
$('#pt-speed').textContent=Math.abs(m.s[5]).toFixed(2)+' rad/s';$('#pt-progress').style.width=Math.min(100,m.hold/p.settle_ticks*100)+'%';for(let j=0;j<2;j++)$('#pt-u'+j).textContent=m.u[j]<0?'↶':m.u[j]>0?'↷':'○';for(const b of helpers.app.querySelectorAll('[data-j]')){b.disabled=full||!m.running;b.dataset.active=String(+b.dataset.u===m.u[+b.dataset.j]);}$('#pt-start').disabled=m.running||m.finished;$('#pt-submit').disabled=m.busy;}
function advance(){if(!m.running)return;const target=Math.min(p.max_ticks,Math.floor((performance.now()-m.startTime+1e-7)/p.tick_ms));while(m.tick<target){const[s,c]=step(m.s,m.u,p);m.s=s;m.contacts+=c;m.tick++;m.hold=settled(s,m.u,p)?m.hold+1:0;}if(m.tick===p.max_ticks)finish();paint();}
function torque(u){advance();if(!m.running||u.every((v,j)=>v===m.u[j]))return;m.u=u;record('torque',{value:[...u],input_source:full?'held_keys':'latched_buttons'});if(u.some(Boolean))m.hold=0;paint();}
function finish(){if(m.finished)return;m.running=false;m.finished=true;record('finish',{state:[...m.s]});paint();}
$('#pt-start').onclick=()=>{if(m.running||m.finished)return;record('start');m.startTime=performance.now();m.running=true;$('.pt-verdict').hidden=true;helpers.setReadout('STUDY IN MOTION · PUSH, RETRACT, SETTLE','idle');paint();};
for(const b of helpers.app.querySelectorAll('[data-j]'))if(!full)b.onclick=()=>{const u=[...m.u];u[+b.dataset.j]=+b.dataset.u;torque(u);};
const keymap={a:[0,-1],d:[0,1],j:[1,-1],l:[1,1]},updateKeys=()=>torque([(keys.has('d')?1:0)-(keys.has('a')?1:0),(keys.has('l')?1:0)-(keys.has('j')?1:0)]);
const down=e=>{const k=e.key.toLowerCase();if(!full||!keymap[k])return;e.preventDefault();if(e.repeat)return;keys.add(k);updateKeys();},up=e=>{const k=e.key.toLowerCase();if(!full||!keymap[k])return;e.preventDefault();keys.delete(k);updateKeys();},blur=()=>{keys.clear();if(full)torque([0,0]);};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
function animate(){advance();frame=requestAnimationFrame(animate);}frame=requestAnimationFrame(animate);
$('#pt-submit').onclick=async()=>{if(m.busy)return;advance();if(!m.events.length)record('start');finish();m.busy=true;paint();try{const r=await(await fetch('/result',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mechanic_id:ID,task_id:state.task_id,challenge_id:state.challenge_id,control_condition:state.control_condition,events:m.events})})).json();if(r.passed){const v=$('.pt-verdict');v.hidden=false;v.querySelector('b').textContent='PASS';v.querySelector('span').textContent='A quiet landing.';helpers.setReadout('PASS · PORCELAIN AT REST','passed');}else if(r.state){await render(r.state,helpers,true);}else{m.busy=false;helpers.setReadout('REJECTED · RETRY SUBMISSION','error');paint();}}catch(e){m.busy=false;helpers.setReadout('SUBMISSION UNAVAILABLE · RETRY','error');paint();}};
cleanup=()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};paint();if(fresh){const v=$('.pt-verdict');v.hidden=false;v.querySelector('b').textContent='FAIL';v.querySelector('span').textContent='Fresh porcelain ready. Begin a new study.';helpers.setReadout('FAIL · FRESH STUDY READY','error');}}
window.WeirdCaptchaMechanics=window.WeirdCaptchaMechanics||{};window.WeirdCaptchaMechanics[ID]={rootSelector:'.porcelain',render};})();
