(() => {
  "use strict";
  let model=null;
  const esc=value=>String(value==null?"":value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
  const wrap=value=>((value+180)%360+360)%360-180;
  function record(kind,details={}){const event={sequence:model.events.length+1,kind,...details};model.events.push(event);return event;}
  function applyDrag(axis,delta){const coupling=model.state.gimbal.coupling,angles=model.angles;angles[axis]=wrap(angles[axis]+delta);if(axis==="outer")angles.inner=wrap(angles.inner+delta*Number(coupling.outer_to_inner));if(axis==="middle")angles.outer=wrap(angles.outer+delta*Number(coupling.middle_to_outer));if(axis==="inner")angles.middle=wrap(angles.middle+delta*Number(coupling.inner_to_middle));}
  function projection(view){const a=model.angles;if(view==="front")return {rotation:a.outer+.32*a.inner,offset:a.middle};if(view==="side")return {rotation:a.middle+.32*a.outer,offset:a.inner};return {rotation:a.inner+.32*a.middle,offset:a.outer};}
  function draw(){const stage=document.querySelector(".gimbal-stage");if(!stage)return;stage.dataset.view=model.view;stage.style.setProperty("--outer-angle",`${model.angles.outer}deg`);stage.style.setProperty("--middle-angle",`${model.angles.middle}deg`);stage.style.setProperty("--inner-angle",`${model.angles.inner}deg`);const p=projection(model.view),needle=document.querySelector(".gimbal-target-needle"),bead=document.querySelector(".gimbal-target-bead");needle.style.rotate=`${p.rotation}deg`;bead.style.translate=`${Math.max(-74,Math.min(74,p.offset*.62))}px 0`;document.querySelectorAll(".gimbal-view").forEach(button=>button.dataset.active=String(button.dataset.view===model.view));}
  function setView(view){model.view=view;record("view",{view});draw();}
  function beginAxisDrag(surface,axis,event,inputSource){event.preventDefault();surface.setPointerCapture(event.pointerId);let last=event.clientX,total=0;surface.dataset.dragging="true";const move=moveEvent=>{if(moveEvent.pointerId!==event.pointerId)return;const dx=moveEvent.clientX-last;last=moveEvent.clientX;const degrees=dx*Number(model.state.gimbal.degrees_per_pixel);total+=degrees;applyDrag(axis,degrees);draw();};const up=upEvent=>{if(upEvent.pointerId!==event.pointerId)return;surface.removeEventListener("pointermove",move);surface.removeEventListener("pointerup",up);surface.removeEventListener("pointercancel",up);surface.dataset.dragging="false";record("drag",{axis,delta:Number(total.toFixed(4)),input_source:inputSource});};surface.addEventListener("pointermove",move);surface.addEventListener("pointerup",up);surface.addEventListener("pointercancel",up);}
  function installControl(control){const axis=control.dataset.axis;if(!model.state.gimbal.active_axes.includes(axis)){control.disabled=true;return;}control.addEventListener("pointerdown",event=>beginAxisDrag(control,axis,event,"axis_controls"));}
  function installDirectControl(stage){stage.addEventListener("pointerdown",event=>{const box=stage.getBoundingClientRect(),distance=Math.hypot(event.clientX-(box.left+box.width/2),event.clientY-(box.top+box.height/2));const axis=distance>120?"outer":distance>75?"middle":"inner";if(model.state.gimbal.active_axes.includes(axis))beginAxisDrag(stage,axis,event,"gimbal_ring_drag");});}
  async function submit(){if(model.submitting)return;model.submitting=true;try{const response=await fetch("/result",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mechanic_id:model.state.mechanic_id,challenge_id:model.state.challenge_id,events:model.events})});const outcome=await response.json();if(outcome.passed===true){model.helpers.setReadout("PASS","passed");document.querySelector(".gimbal-captcha").classList.add("is-passed");}else{model.helpers.setReadout("FAIL","error");setTimeout(()=>outcome.state&&model.helpers.render(outcome.state),850);}}catch(_error){model.submitting=false;model.helpers.setReadout("FAIL","error");}}
  async function render(state,helpers){document.body.dataset.mechanic="gimbal-upright-v2";state.gimbal.active_axes=state.gimbal.active_axes||["outer","middle","inner"];const interaction=state.control_condition?.interaction||"simplified";model={state,helpers,interaction,angles:{...state.gimbal.initial},view:state.gimbal.views[0],events:[],submitting:false};const controls=interaction==="simplified"?`<div class="gimbal-controls"><button class="gimbal-control control-outer" data-axis="outer" type="button"><i></i></button><button class="gimbal-control control-middle" data-axis="middle" type="button"><i></i></button><button class="gimbal-control control-inner" data-axis="inner" type="button"><i></i></button></div>`:`<div class="gimbal-direct-note">DRAG THE OUTER MIDDLE OR INNER RING</div>`;helpers.app.innerHTML=`<section class="gimbal-captcha" data-interaction="${esc(interaction)}"><header><span>TRI-AXIS ORIENTATION CHAMBER</span><h1>${esc(state.prompt)}</h1><div class="gimbal-viewbank">${state.gimbal.views.map((view,index)=>`<button class="gimbal-view" type="button" data-view="${view}" data-active="${index===0}">${["Ⅰ","Ⅱ","Ⅲ"][index]}</button>`).join("")}</div></header><section class="gimbal-stage" data-view="${esc(model.view)}" style="--target-needle-width:${Number(state.gimbal.target_needle_width||4)}px"><div class="plumb-line"><i></i><b></b></div><div class="gimbal-rig"><div class="gimbal-ring ring-outer"><div class="gimbal-ring ring-middle"><div class="gimbal-ring ring-inner"><div class="gimbal-mark"><span>UP</span><i></i></div></div></div></div><div class="gimbal-target-needle"></div><div class="gimbal-target-bead"></div></div><div class="view-mask"><i></i><i></i><i></i></div></section><footer>${controls}<div class="readout" data-status="idle"></div><button class="gimbal-submit" type="button">CERTIFY</button></footer></section>`;document.querySelectorAll(".gimbal-view").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.view)));if(interaction==="simplified")document.querySelectorAll(".gimbal-control").forEach(installControl);else installDirectControl(document.querySelector(".gimbal-stage"));document.querySelector(".gimbal-submit").addEventListener("click",submit);draw();}
  window.WeirdCaptchaMechanics=window.WeirdCaptchaMechanics||{};window.WeirdCaptchaMechanics.rotate_wrong_thing_upright={render,rootSelector:".gimbal-captcha"};
})();
