(()=>{'use strict';
const ID='timber_knot_release';let cleanup;
const AXES=['x','y','z'], COLORS={ochre:'#d8a65c',vermilion:'#d66a52',indigo:'#718ed1',moss:'#8fae73',saffron:'#e7c46b',plum:'#b783b7'};
function cells(piece,offset){return piece.voxels.map(c=>[c[0]+offset[0],c[1]+offset[1],c[2]+offset[2]]);}
function sweptClear(piece,old,nw,others){const delta=nw.map((v,i)=>v-old[i]),axes=delta.map((v,i)=>v?i:-1).filter(i=>i>=0);if(axes.length!==1||![-1,1].includes(delta[axes[0]]))return false;const axis=axes[0],moving=cells(piece,old);for(const other of others){for(const a of moving)for(const b of cells(other,other.offset)){if([0,1,2].some(i=>i!==axis&&a[i]!==b[i]))continue;const lo=Math.min(a[axis],a[axis]+delta[axis]),hi=Math.max(a[axis],a[axis]+delta[axis]);if(Math.max(lo,b[axis])<Math.min(hi+1,b[axis]+1))return false;}}return true;}
function rot(v,yaw,pitch){const x=Math.cos(yaw)*v[0]-Math.sin(yaw)*v[1],y=Math.sin(yaw)*v[0]+Math.cos(yaw)*v[1];return[x,Math.cos(pitch)*y-Math.sin(pitch)*v[2],Math.sin(pitch)*y+Math.cos(pitch)*v[2]];}
function makeProjection(model){const scale=model.viewScale||58,ox=model.viewOriginX??450,oy=model.viewOriginY??286;return v=>{const q=rot(v,model.yaw,model.pitch);return[ox+q[0]*scale,oy+q[1]*scale*.638-q[2]*scale*.931];};}
function axisVector(model,axis){const p=makeProjection(model),a=p([0,0,0]),b=p(axis==='x'?[1,0,0]:axis==='y'?[0,1,0]:[0,0,1]);const d=[b[0]-a[0],b[1]-a[1]],len=Math.hypot(...d)||1;return[d[0]/len,d[1]/len];}
function center(model,piece){const q=piece.voxels.reduce((a,c)=>[a[0]+c[0],a[1]+c[1],a[2]+c[2]],[0,0,0]);q[0]=q[0]/piece.voxels.length+piece.offset[0]+.5;q[1]=q[1]/piece.voxels.length+piece.offset[1]+.5;q[2]=q[2]/piece.voxels.length+piece.offset[2]+.5;return makeProjection(model)(q);}
function fitView(model,state){const points=[];for(const x of [-4,4])for(const y of [-4,4])for(const z of [-4,4])points.push(rot([x,y,z],model.yaw,model.pitch));for(const piece of state.pieces)if(!model.released.has(piece.id))for(const cell of cells(piece,model.pieces.find(q=>q.id===piece.id).offset))for(const x of [cell[0],cell[0]+1])for(const y of [cell[1],cell[1]+1])for(const z of [cell[2],cell[2]+1])points.push(rot([x,y,z],model.yaw,model.pitch));const uv=points.map(q=>[q[0],q[1]*.638-q[2]*.931]),minU=Math.min(...uv.map(q=>q[0])),maxU=Math.max(...uv.map(q=>q[0])),minV=Math.min(...uv.map(q=>q[1])),maxV=Math.max(...uv.map(q=>q[1])),margin=54;model.viewScale=Math.min(58,(900-2*margin)/Math.max(1,maxU-minU),(560-2*margin)/Math.max(1,maxV-minV));model.viewOriginX=450-(minU+maxU)*model.viewScale/2;model.viewOriginY=280-(minV+maxV)*model.viewScale/2;}
function paint(ctx,model,state,app){fitView(model,state);const p=makeProjection(model),W=900,H=560;ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#172b32');g.addColorStop(1,'#09171c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#29444a';ctx.lineWidth=1;for(let i=-5;i<=5;i++){let a=p([i,-5,-4]),b=p([i,5,-4]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();a=p([-5,i,-4]);b=p([5,i,-4]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();}
 const origin=p([0,0,0]);ctx.strokeStyle='#d4b56a88';ctx.lineWidth=2;ctx.setLineDash([7,6]);ctx.strokeRect(origin[0]-142,origin[1]-118,284,236);ctx.setLineDash([]);ctx.fillStyle='#cdb77c';ctx.font='11px Arial';ctx.fillText('CLEARANCE FRAME',origin[0]-61,origin[1]+133);const decoys=Number(state.decoy_seams||0);ctx.strokeStyle='#b99a7d88';ctx.lineWidth=2;ctx.setLineDash([4,4]);for(let i=0;i<decoys;i++){const d=p([((i*3)%5)-2,((i*2+1)%5)-2,1]);ctx.beginPath();ctx.arc(d[0],d[1],7+i*2,0,Math.PI*2);ctx.stroke();}ctx.setLineDash([]);
 const live=state.pieces.filter(x=>!model.released.has(x.id));const cubes=[];for(const piece of live){for(const cell of cells(piece,piece.offset))cubes.push({piece,cell,depth:cell[0]+cell[1]-cell[2]});}cubes.sort((a,b)=>a.depth-b.depth);
 function poly(points,color){ctx.beginPath();ctx.moveTo(...points[0]);for(const q of points.slice(1))ctx.lineTo(...q);ctx.closePath();ctx.fillStyle=color;ctx.fill();ctx.strokeStyle='#3e3024';ctx.lineWidth=1;ctx.stroke();}
 for(const item of cubes){const c=item.cell,base=[c[0],c[1],c[2]],q=[p(base),p([c[0]+1,c[1],c[2]]),p([c[0]+1,c[1]+1,c[2]]),p([c[0],c[1]+1,c[2]])],top=[p([c[0],c[1],c[2]+1]),p([c[0]+1,c[1],c[2]+1]),p([c[0]+1,c[1]+1,c[2]+1]),p([c[0],c[1]+1,c[2]+1])],col=COLORS[item.piece.color]||'#c99';poly([top[0],top[1],top[2],top[3]],col);poly([q[0],q[1],top[1],top[0]],col+'cc');poly([q[1],q[2],top[2],top[1]],col+'99');}
 for(const piece of live){const c=center(model,piece),v=axisVector(model,piece.axis),sign=piece.exit_sign;ctx.fillStyle='#f4ead4';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.fillText(piece.label,c[0],c[1]-18);ctx.strokeStyle='#f4ead488';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(c[0]-v[0]*18,c[1]-v[1]*18);ctx.lineTo(c[0]+v[0]*sign*28,c[1]+v[1]*sign*28);ctx.stroke();ctx.beginPath();ctx.moveTo(c[0]+v[0]*sign*28,c[1]+v[1]*sign*28);ctx.lineTo(c[0]+v[0]*sign*18-v[1]*5,c[1]+v[1]*sign*18+v[0]*5);ctx.lineTo(c[0]+v[0]*sign*18+v[1]*5,c[1]+v[1]*sign*18-v[0]*5);ctx.fillStyle='#f4ead4';ctx.fill();}
 ctx.textAlign='left';ctx.fillStyle='#acc6c2';ctx.font='12px Arial';ctx.fillText(`CAMERA  yaw ${(model.yaw*180/Math.PI).toFixed(0)}°  ·  pitch ${(model.pitch*180/Math.PI).toFixed(0)}°`,22,28);ctx.fillText('GOLD ARROWS SHOW EACH BEAM\'S PERMITTED EXIT AXIS',22,49);ctx.fillStyle='#eddbad';ctx.fillText(`RELEASED  ${model.released.size} / ${state.pieces.length}`,22,526);ctx.fillStyle='#85a99a';ctx.fillText('A partial shift can expose a new seam. Touch the wood, not the empty space.',390,526);
 const buttons=app.querySelectorAll('[data-piece-button]');for(const b of buttons){const id=b.dataset.pieceButton;b.disabled=model.released.has(id)||!model.started;b.dataset.active=String(model.selected===id);}
 app.querySelector('#tk-submit').disabled=!model.started||model.busy;app.querySelector('#tk-start').disabled=model.started||model.finished;app.querySelector('#tk-count').textContent=`${model.released.size}/${state.pieces.length}`;
}
async function render(state,helpers,fresh=false){if(cleanup)cleanup();document.body.dataset.mechanic=ID;const full=(state.control_condition?.interaction||'full')==='full';const model={yaw:Number(state.scene?.camera?.yaw||.52),pitch:Number(state.scene?.camera?.pitch||.48),started:false,finished:false,busy:false,selected:null,drag:null,released:new Set(),moves:Object.fromEntries(state.pieces.map(p=>[p.id,0])),events:[],pieces:state.pieces.map(p=>({...p,offset:[...p.offset]}))};window.timberKnotModel=model;const app=helpers.app;app.innerHTML=`<section class="timber-knot" data-challenge-id="${state.challenge_id}"><header><div><small>JOINERY ROOM / DISASSEMBLY STUDY</small><h1>Timber Knot Release</h1></div><span class="tk-stamp">HAND-CUT<br>NO GLUE</span></header><div class="tk-layout"><div class="tk-stage"><canvas width="900" height="560" aria-label="Isometric timber knot with carved beams and clearance frame"></canvas><div class="tk-overlay" aria-live="polite"><b id="tk-count">0/${state.pieces.length}</b><span>BEAMS RELEASED</span></div></div><aside><small>THE RELEASE TEST</small><h2>Open the knot<br>one seam at a time.</h2><p>Every beam slides on one axis. A move is accepted only when its whole voxel body clears the other timber through the complete one-cell sweep.</p><div class="tk-rule"><b>VISIBLE RULE</b><span>Move toward each beam's gold arrow. A beam leaves the frame after ${state.difficulty.extraction_steps} accepted cells.</span></div><div class="tk-pieces">${state.pieces.map(p=>`<div class="tk-piece" data-piece-button="true" data-piece-button="${p.id}"><div><b style="color:${COLORS[p.color]||'#fff'}">${p.label}</b><small>AXIS ${p.axis.toUpperCase()} · ${p.exit_sign>0?'FORWARD':'BACK'} · ${p.voxel_count} VOXELS</small></div><button data-select="${p.id}" aria-label="Select ${p.label}">SELECT</button><button data-step="${p.id}" aria-label="Step ${p.label} one cell">STEP ${p.exit_sign>0?'→':'←'}</button></div>`).join('')}</div><div class="tk-camera"><button data-orbit="-1">ORBIT ◀</button><button data-orbit="1">ORBIT ▶</button></div><p class="tk-hint">${full?'Full interaction: drag a beam along its gold arrow; drag empty canvas to orbit.':'Simplified interaction: select a beam and click its one-cell step proxy. Orbit buttons inspect the knot.'}</p><button id="tk-start">BEGIN RELEASE</button></aside></div><footer><div class="tk-readout" data-status="idle">READY · FIND THE FIRST CLEARANCE</div><button id="tk-submit">CERTIFY RELEASE</button></footer></section>`;
 const canvas=app.querySelector('canvas'),ctx=canvas.getContext('2d'),$=s=>app.querySelector(s);let frame;
 const status=(text,kind='idle')=>helpers.setReadout(text,kind);
 const record=(kind,extra={})=>model.events.push({sequence:model.events.length+1,kind,...extra});
 function movePiece(id,requested,source){if(!model.started||model.released.has(id))return false;const piece=model.pieces.find(p=>p.id===id),sign=piece.exit_sign;if(requested!==sign){status('BLOCKED · THAT FACE HAS NO CLEARANCE','error');return false;}const old=[...piece.offset],nw=[...old];nw[piece.axis_index]+=requested;const others=model.pieces.filter(q=>q.id!==id&&!model.released.has(q.id)).map(q=>({...q,offset:q.offset}));if(!sweptClear(piece,old,nw,others)){status(`${piece.label} · SOLID CONTACT · TRY ANOTHER BEAM`,'error');return false;}record('move',{piece:id,axis:piece.axis,direction:requested,from:old,to:nw,input_source:source});piece.offset=nw;model.moves[id]++;if(model.moves[id]===state.difficulty.extraction_steps){model.released.add(id);model.selected=null;status(`${piece.label} RELEASED · CLEARANCE OPEN`,'idle');}else status(`${piece.label} SHIFTED · INSPECT THE NEW SEAM`,'idle');paint(ctx,model,state,app);return true;}
 function hit(x,y){let best=null,d=Infinity;for(const p of model.pieces)if(!model.released.has(p.id)){const c=center(model,p),z=Math.hypot(c[0]-x,c[1]-y);if(z<d&&z<75){best=p;d=z;}}return best;}
 const down=e=>{if(!model.started)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*900/r.width,y=(e.clientY-r.top)*560/r.height,piece=hit(x,y);model.drag={x,y,piece,lastX:x,lastY:y,orbit:!piece};canvas.setPointerCapture?.(e.pointerId);if(piece&&!full)model.selected=piece.id;};
 const move=e=>{if(!model.drag)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*900/r.width,y=(e.clientY-r.top)*560/r.height;if(model.drag.orbit){model.yaw+=(x-model.drag.lastX)*.012;model.pitch=Math.max(.18,Math.min(1.05,model.pitch+(y-model.drag.lastY)*.009));model.drag.lastX=x;model.drag.lastY=y;paint(ctx,model,state,app);}};
 const up=e=>{if(!model.drag)return;const d=model.drag;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*900/r.width,y=(e.clientY-r.top)*560/r.height;model.drag=null;if(d.orbit){if(Math.hypot(x-d.x,y-d.y)>5)record('orbit',{input_source:full?'camera_drag':'orbit_button',yaw:model.yaw,pitch:model.pitch});paint(ctx,model,state,app);return;}if(full&&d.piece){const v=axisVector(model,d.piece.axis),dx=x-d.x,dy=y-d.y;const dot=dx*v[0]+dy*v[1],requested=dot>=0?1:-1;movePiece(d.piece.id,requested,'direct_drag');}};
 canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);
 $('[data-orbit="-1"]').onclick=()=>{model.yaw-=.28;record('orbit',{input_source:'orbit_button',yaw:model.yaw,pitch:model.pitch});paint(ctx,model,state,app);};$('[data-orbit="1"]').onclick=()=>{model.yaw+=.28;record('orbit',{input_source:'orbit_button',yaw:model.yaw,pitch:model.pitch});paint(ctx,model,state,app);};
 for(const b of app.querySelectorAll('[data-select]'))b.onclick=()=>{if(!model.started||full)return;const id=b.dataset.select;if(model.released.has(id))return;model.selected=id;record('select',{piece:id,input_source:'beam_select'});status(`${id.toUpperCase()} SELECTED · USE ITS GOLD STEP`,'idle');paint(ctx,model,state,app);};
 for(const b of app.querySelectorAll('[data-step]'))b.onclick=()=>{if(!model.started||full)return;const id=b.dataset.step,piece=model.pieces.find(p=>p.id===id);if(model.selected!==id){status('SELECT A BEAM BEFORE USING ITS STEP PROXY','error');return;}movePiece(id,piece.exit_sign,'proxy_step');};
 const start=()=>{if(model.started)return;model.started=true;record('start');status('STUDY IN MOTION · OPEN A CLEARANCE','idle');paint(ctx,model,state,app);};$('#tk-start').onclick=start;
 const submit=async()=>{if(model.busy)return;model.busy=true;model.finished=true;const all=model.released.size===model.pieces.length;record('finish',{input_source:'certify_button',completed:all,released:[...model.released]});paint(ctx,model,state,app);try{const response=await(await fetch('/result',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mechanic_id:ID,task_id:state.task_id,challenge_id:state.challenge_id,control_condition:state.control_condition,interaction_mode:full?'full':'simplified',events:model.events})})).json();if(response.passed){const read=app.querySelector('.tk-readout');read.textContent='PASS · EVERY BEAM RELEASED';read.dataset.status='passed';const overlay=app.querySelector('.tk-overlay');overlay.classList.add('passed');overlay.innerHTML='<b>PASS</b><span>THE KNOT IS OPEN</span>';}else if(response.state){await render(response.state,helpers,true);}else{model.busy=false;model.finished=false;status('REJECTED · RETRY THE CURRENT KNOT','error');paint(ctx,model,state,app);}}catch(err){model.busy=false;model.finished=false;status('SUBMISSION UNAVAILABLE · RETRY','error');paint(ctx,model,state,app);}};$('#tk-submit').onclick=submit;
 const keydown=e=>{if(!full||!model.started||e.repeat)return;};window.addEventListener('keydown',keydown);cleanup=()=>{cancelAnimationFrame(frame);canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);window.removeEventListener('keydown',keydown);};paint(ctx,model,state,app);if(fresh){status('FAIL · FRESH KNOT READY','error');app.querySelector('.tk-overlay').classList.add('fresh');}}
 window.WeirdCaptchaMechanics=window.WeirdCaptchaMechanics||{};window.TimberKnotModel={sweptClear,axisVector,center};window.WeirdCaptchaMechanics[ID]={rootSelector:'.timber-knot',render};
})();
